# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lightly = {
    pname = "lightly";
    version = "121a61e5b67e5122449c80301e41b4de3649b0d5";
    src = fetchFromGitHub {
      owner = "Luwx";
      repo = "lightly";
      rev = "121a61e5b67e5122449c80301e41b4de3649b0d5";
      fetchSubmodules = false;
      sha256 = "sha256-UmttzKFkuZupFpBrTQYIsLCpNRLcd5CkabQN5n5zkJQ=";
    };
    date = "2022-05-02";
  };
}
