#!/bin/sh
Selection=true

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrdb $HOME/.Xresources
xmodmap $HOME/.Xmodmap

export EMPTTY_LOADED=true

# QT5 themes to GNOME
export QT_QPA_PLATFORMTHEME=qt5ct
export GTK_USE_PORTAL=1
export QT_STYLE_OVERRIDE=kvantum

# echo $@ > /home/ayats/emptty.log
dex -a -e $@

exec dbus-launch $@
