# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hlargs = {
    pname = "hlargs";
    version = "88b925d699fb39633cdda02c24f0b3ba5d0e6964";
    src = fetchFromGitHub ({
      owner = "m-demare";
      repo = "hlargs.nvim";
      rev = "88b925d699fb39633cdda02c24f0b3ba5d0e6964";
      fetchSubmodules = false;
      sha256 = "sha256-0N89OjtY7faw6vyCDHGyXFEboluAPj5K+z6csopWJYM=";
    });
    date = "2022-12-14";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "d41f301dcd3de51e95d5e1b7737e22a4e1eddd28";
    src = fetchFromGitHub ({
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "d41f301dcd3de51e95d5e1b7737e22a4e1eddd28";
      fetchSubmodules = false;
      sha256 = "sha256-raTRS5mYj5r2nT3x7FfR8CnP6trdAL7vvL/sDixRnbY=";
    });
    date = "2023-01-29";
  };
  nvim-transparent = {
    pname = "nvim-transparent";
    version = "6816751e3d595b3209aa475a83b6fbaa3a5ccc98";
    src = fetchFromGitHub ({
      owner = "xiyaowong";
      repo = "nvim-transparent";
      rev = "6816751e3d595b3209aa475a83b6fbaa3a5ccc98";
      fetchSubmodules = false;
      sha256 = "sha256-j1PO0r2q5w0fJvO7BG0xXDjIdOVl73eGO1rclB221uw=";
    });
    date = "2022-12-28";
  };
}
