# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hlargs = {
    pname = "hlargs";
    version = "07771b0e802dd11d788a5de3ef84778a63f93802";
    src = fetchFromGitHub ({
      owner = "m-demare";
      repo = "hlargs.nvim";
      rev = "07771b0e802dd11d788a5de3ef84778a63f93802";
      fetchSubmodules = false;
      sha256 = "sha256-zNPu0zoNldCRZGTo7r2wVa39WYxWvrmhhhw74vzWyH0=";
    });
    date = "2023-03-25";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "18ce3c5f694aaac31f5a434937ca6abe02b83f92";
    src = fetchFromGitHub ({
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "18ce3c5f694aaac31f5a434937ca6abe02b83f92";
      fetchSubmodules = false;
      sha256 = "sha256-XpHkJZVfvvWwutw8cUkSLbVo9gqH/C3G/CfjTCl8y6M=";
    });
    date = "2023-03-30";
  };
  nvim-transparent = {
    pname = "nvim-transparent";
    version = "2d8d650fc8a3b8da6a01031295547295eb473b7d";
    src = fetchFromGitHub ({
      owner = "xiyaowong";
      repo = "nvim-transparent";
      rev = "2d8d650fc8a3b8da6a01031295547295eb473b7d";
      fetchSubmodules = false;
      sha256 = "sha256-6NmVgXlA7Afwwf+XEXJRAp1LIvaFTEQbxg1u1Hqoq1A=";
    });
    date = "2023-03-24";
  };
}
