# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  iosevka = {
    pname = "iosevka";
    version = "v1.6.2";
    src = fetchurl {
      url = "https://github.com/viperML/iosevka/releases/download/v1.6.2/release.zip";
      sha256 = "sha256-4U9zm/lpalqwJQ1BHPXC/A5U71pvUax2Kg6Bv57+eWE=";
    };
  };
}
