#!/usr/bin/env bash
set -euo pipefail

VSCODE_SERVER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo "Got vscode directory : $VSCODE_SERVER_DIR"

echo "Patching nodejs binaries..."

interpreter="$(cat $(nix eval --raw nixpkgs#stdenv.cc)/nix-support/dynamic-linker)"
rpath="$(nix eval --raw nixpkgs#stdenv.cc.cc.lib)/lib"

for versiondir in $VSCODE_SERVER_DIR/bin/*/; do
    nix run nixpkgs#patchelf -- --set-interpreter "$interpreter" --set-rpath "$rpath" $versiondir/node
done
