# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wl-clip-persist = {
    pname = "wl-clip-persist";
    version = "e2abc48f242dd8d8cb17f5d641243869e0425fd3";
    src = fetchgit {
      url = "https://github.com/Linus789/wl-clip-persist";
      rev = "e2abc48f242dd8d8cb17f5d641243869e0425fd3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gUi4Htui7IwldeK30C7SGTNc+0VHuzDZfJdaL8FmkGs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wl-clip-persist-e2abc48f242dd8d8cb17f5d641243869e0425fd3/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2024-04-29";
  };
}
