# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wl-clip-persist = {
    pname = "wl-clip-persist";
    version = "d9fc91734d482e95e80405df8da11547c41881d5";
    src = fetchgit {
      url = "https://github.com/Linus789/wl-clip-persist";
      rev = "d9fc91734d482e95e80405df8da11547c41881d5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dFhHsBazBHVWgPxoRDNwh8Yctt4w64E0RyFaHEC4mvk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wl-clip-persist-d9fc91734d482e95e80405df8da11547c41881d5/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2024-05-03";
  };
}
