# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wl-clip-persist = {
    pname = "wl-clip-persist";
    version = "6ba11a2aa295d780f0b2e8f005cf176601d153b0";
    src = fetchgit {
      url = "https://github.com/Linus789/wl-clip-persist";
      rev = "6ba11a2aa295d780f0b2e8f005cf176601d153b0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wg4xEXLAZpWflFejP7ob4cnmRvo9d/0dL9hceG+RUr0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wl-clip-persist-6ba11a2aa295d780f0b2e8f005cf176601d153b0/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2022-09-07";
  };
}
