# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  glab = {
    pname = "glab";
    version = "14eef951111b05173730909a25bf6d7d0b6091ef";
    src = fetchgit {
      url = "https://gitlab.com/gitlab-community/gitlab-org/cli";
      rev = "14eef951111b05173730909a25bf6d7d0b6091ef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UL1EmmzsKQVMm95Xg5db82w9caVbihabj1r2Wb5+3lY=";
    };
    date = "2026-03-30";
  };
}
