# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bufferline-nvim = {
    pname = "bufferline-nvim";
    version = "v4.7.0";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "v4.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-QWZB3C9XFVBRurUfYj0orr6LLP7eI6vYhkKsrdG+wZI=";
    };
  };
  cmp-async-path = {
    pname = "cmp-async-path";
    version = "7df7f3721c45aac26b6e0474087538f4681c9c7a";
    src = fetchgit {
      url = "https://codeberg.org/FelipeLema/cmp-async-path";
      rev = "7df7f3721c45aac26b6e0474087538f4681c9c7a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-LSWWsn8aKogjWevcbjITXu30a2k3wY3+f2+l7WDAZpY=";
    };
    date = "2024-03-25";
  };
  cmp-cmdline = {
    pname = "cmp-cmdline";
    version = "d250c63aa13ead745e3a40f61fdd3470efde3923";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "d250c63aa13ead745e3a40f61fdd3470efde3923";
      fetchSubmodules = false;
      sha256 = "sha256-iBmXp+gUSMbgfkv7c7RDQAwPq02e07wEnBETP0dWBOo=";
    };
    date = "2024-03-22";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
      fetchSubmodules = false;
      sha256 = "sha256-CT1+Z4XJBVsl/RqvJeGmyitD6x7So0ylXvvef5jh7I8=";
    };
    date = "2024-05-17";
  };
  conform-nvim = {
    pname = "conform-nvim";
    version = "v7.1.0";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "conform.nvim";
      rev = "v7.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-THl44vHBvgdaYXAUl6g1ccR2mYTBBVizgnqT2MbRngw=";
    };
  };
  fidget-nvim = {
    pname = "fidget-nvim";
    version = "d855eed8a06531a7e8fd0684889b2943f373c469";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "d855eed8a06531a7e8fd0684889b2943f373c469";
      fetchSubmodules = false;
      sha256 = "sha256-fjxdRN08BMU7jTWdhdzh8kW18ZURS9SJCwnTxuz6aFE=";
    };
    date = "2024-07-13";
  };
  git-conflict-nvim = {
    pname = "git-conflict-nvim";
    version = "45cde6f0acf26d0e4b64acfa45349dd1da01e577";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "git-conflict.nvim";
      rev = "45cde6f0acf26d0e4b64acfa45349dd1da01e577";
      fetchSubmodules = false;
      sha256 = "sha256-SablEni7+VYXUs5lkgpZBqzIBWDE2p3f+R4vXrzF+oE=";
    };
    date = "2024-06-26";
  };
  gitsigns-nvim = {
    pname = "gitsigns-nvim";
    version = "v0.9.0";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "v0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-AbnjBqKLhOGMGBXBnu9zbL3PG7rKmAoYtxY17kzFEIA=";
    };
  };
  guess-indent-nvim = {
    pname = "guess-indent-nvim";
    version = "6cd61f7a600bb756e558627cd2e740302c58e32d";
    src = fetchFromGitHub {
      owner = "NMAC427";
      repo = "guess-indent.nvim";
      rev = "6cd61f7a600bb756e558627cd2e740302c58e32d";
      fetchSubmodules = false;
      sha256 = "sha256-mzX9LgG2+9aj2lMPlSZh3zP3wphHQdecXe7RHP1baT0=";
    };
    date = "2024-07-06";
  };
  indent-blankline-nvim = {
    pname = "indent-blankline-nvim";
    version = "v3.7.2";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "v3.7.2";
      fetchSubmodules = false;
      sha256 = "sha256-/2PpfXVXFd6adzdizcpCvLftOELuWr3OJja00pr2yG8=";
    };
  };
  lualine-nvim = {
    pname = "lualine-nvim";
    version = "b431d228b7bbcdaea818bdc3e25b8cdbe861f056";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "b431d228b7bbcdaea818bdc3e25b8cdbe861f056";
      fetchSubmodules = false;
      sha256 = "sha256-gCm7m96PkZyrgjmt7Efc+NMZKStAq1zr7JRCYOgGDuE=";
    };
    date = "2024-08-12";
  };
  minintro-nvim = {
    pname = "minintro-nvim";
    version = "b7fa58cc549e8d2b362a217a7620d9aedc47d47e";
    src = fetchFromGitHub {
      owner = "eoh-bse";
      repo = "minintro.nvim";
      rev = "b7fa58cc549e8d2b362a217a7620d9aedc47d47e";
      fetchSubmodules = false;
      sha256 = "sha256-3yOT4sve3LZ2lO15XlX8OkCJFE/r1ARo41x01CjGIbA=";
    };
    date = "2023-11-21";
  };
  neo-tree-nvim = {
    pname = "neo-tree-nvim";
    version = "206241e451c12f78969ff5ae53af45616ffc9b72";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "206241e451c12f78969ff5ae53af45616ffc9b72";
      fetchSubmodules = false;
      sha256 = "sha256-eNGuQEjAKsPuRDGaw95kCVOmP64ZDnUuFBppqtcrhZ4=";
    };
    date = "2024-06-11";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "cbaebd92dce84e9ba63cb07d3199e5a19b204c1a";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "cbaebd92dce84e9ba63cb07d3199e5a19b204c1a";
      fetchSubmodules = false;
      sha256 = "sha256-HnNbB5Nx65Zb5oTjED0et+bAAEVX5+8pZxwTZvxRtQ8=";
    };
    date = "2024-08-02";
  };
  nui-nvim = {
    pname = "nui-nvim";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-L0ebXtv794357HOAgT17xlEJsmpqIHGqGlYfDB20WTo=";
    };
  };
  nvim-autopairs = {
    pname = "nvim-autopairs";
    version = "48ca9aaee733911424646cb1605f27bc01dedbe3";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "48ca9aaee733911424646cb1605f27bc01dedbe3";
      fetchSubmodules = false;
      sha256 = "sha256-KAtr/IYABHZhva9q7lqvp1ymryz547gyR8NdLwfo9gQ=";
    };
    date = "2024-08-10";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "ae644feb7b67bf1ce4260c231d1d4300b19c6f30";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "ae644feb7b67bf1ce4260c231d1d4300b19c6f30";
      fetchSubmodules = false;
      sha256 = "sha256-NcodgUp8obTsjgc+5j2dKr0f3FelYikQTJngfZXRZzo=";
    };
    date = "2024-08-01";
  };
  nvim-dap = {
    pname = "nvim-dap";
    version = "0.8.0";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-jdNqA2POc2TEspkgbJdxgnczVEJnBBi+nipTXCPQgyM=";
    };
  };
  nvim-dap-python = {
    pname = "nvim-dap-python";
    version = "d777c2b32ed39f61209c09bede28d7491621a631";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "d777c2b32ed39f61209c09bede28d7491621a631";
      fetchSubmodules = false;
      sha256 = "sha256-W1GGJAd+1z+ReOrosFua0V7c4VDMsNcrPAQ5FXK0Trs=";
    };
    date = "2024-06-26";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "v0.1.8";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "v0.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-foJ7a59N0a3QaBW24PtwbyYDQVlIsFxiatADLO/hQvc=";
    };
  };
  nvim-paredit = {
    pname = "nvim-paredit";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "julienvincent";
      repo = "nvim-paredit";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-rls94nrAlPYpHDXp0eB4UzlLRB5HriBuZMdLGVAzGmA=";
    };
  };
  nvim-paredit-scheme = {
    pname = "nvim-paredit-scheme";
    version = "3e5838290dd57116457e4b11eb6ba21e83b260a4";
    src = fetchFromGitHub {
      owner = "ekaitz-zarraga";
      repo = "nvim-paredit-scheme";
      rev = "3e5838290dd57116457e4b11eb6ba21e83b260a4";
      fetchSubmodules = false;
      sha256 = "sha256-gzZJlN8LO1SH0joqgQgGIlkCVreccF8yxRYoinB9tU0=";
    };
    date = "2024-01-27";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "3722e3d1fb5fe1896a104eb489e8f8651260b520";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "3722e3d1fb5fe1896a104eb489e8f8651260b520";
      fetchSubmodules = false;
      sha256 = "sha256-TeWMlfNTA5+tiPq6D2TVWjdfJVr3FOwpqUDU8kfFZ8E=";
    };
    date = "2024-08-04";
  };
  org-bullets-nvim = {
    pname = "org-bullets-nvim";
    version = "7e76e04827ac3fb13fc645a6309ac14203c4ca6a";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "org-bullets.nvim";
      rev = "7e76e04827ac3fb13fc645a6309ac14203c4ca6a";
      fetchSubmodules = false;
      sha256 = "sha256-bxiL88uUa0Zd/HL7RcC/XVhbkgdlFr6MmlQfkpxFybE=";
    };
    date = "2024-07-09";
  };
  orgmode = {
    pname = "orgmode";
    version = "0.3.4";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "orgmode";
      rev = "0.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-SmofuYt4fLhtl5qedYlmCRgOmZaw3nmlnMg0OMzyKnM=";
    };
  };
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
      fetchSubmodules = false;
      sha256 = "sha256-5Jf2mWFVDofXBcXLbMa417mqlEPWLA+cQIZH/vNEV1g=";
    };
    opt = "false";
    date = "2024-05-20";
  };
  telescope-fzf-native-nvim = {
    pname = "telescope-fzf-native-nvim";
    version = "cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-fzf-native.nvim";
      rev = "cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b";
      fetchSubmodules = false;
      sha256 = "sha256-GEhPf1f0jkEuDlHNuxVko0ChvuF/zoQroLNUlk8N5EA=";
    };
    date = "2024-07-02";
  };
  telescope-nvim = {
    pname = "telescope-nvim";
    version = "0.1.8";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "0.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-e1ulhc4IIvUgpjKQrSqPY4WpXuez6wlxL6Min9U0o5Q=";
    };
  };
  vim-nix = {
    pname = "vim-nix";
    version = "e25cd0f2e5922f1f4d3cd969f92e35a9a327ffb0";
    src = fetchFromGitHub {
      owner = "LnL7";
      repo = "vim-nix";
      rev = "e25cd0f2e5922f1f4d3cd969f92e35a9a327ffb0";
      fetchSubmodules = false;
      sha256 = "sha256-2/9eyU+uUbcKiNcBDdgdxCBp1vNSP51U/0LTHihEYJY=";
    };
    date = "2024-02-24";
  };
  which-key-nvim = {
    pname = "which-key-nvim";
    version = "v3.13.2";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "v3.13.2";
      fetchSubmodules = false;
      sha256 = "sha256-nv9s4/ax2BoL9IQdk42uN7mxIVFYiTK+1FVvWDKRnGM=";
    };
  };
}
