# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bufferline-nvim = {
    pname = "bufferline-nvim";
    version = "v4.7.0";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "v4.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-QWZB3C9XFVBRurUfYj0orr6LLP7eI6vYhkKsrdG+wZI=";
    };
  };
  cmp-buffer = {
    pname = "cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  cmp-cmdline = {
    pname = "cmp-cmdline";
    version = "d250c63aa13ead745e3a40f61fdd3470efde3923";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "d250c63aa13ead745e3a40f61fdd3470efde3923";
      fetchSubmodules = false;
      sha256 = "sha256-iBmXp+gUSMbgfkv7c7RDQAwPq02e07wEnBETP0dWBOo=";
    };
    date = "2024-03-22";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
      fetchSubmodules = false;
      sha256 = "sha256-CT1+Z4XJBVsl/RqvJeGmyitD6x7So0ylXvvef5jh7I8=";
    };
    date = "2024-05-17";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  comment-nvim = {
    pname = "comment-nvim";
    version = "e30b7f2008e52442154b66f7c519bfd2f1e32acb";
    src = fetchFromGitHub {
      owner = "numToStr";
      repo = "Comment.nvim";
      rev = "e30b7f2008e52442154b66f7c519bfd2f1e32acb";
      fetchSubmodules = false;
      sha256 = "sha256-h0kPue5Eqd5aeu4VoLH45pF0DmWWo1d8SnLICSQ63zc=";
    };
    date = "2024-06-09";
  };
  conform-nvim = {
    pname = "conform-nvim";
    version = "v7.0.0";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "conform.nvim";
      rev = "v7.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-0gBvpqsBn7KlpIPANPa3nf2TC7EBm4s47V+TFbr7RVU=";
    };
  };
  lualine-nvim = {
    pname = "lualine-nvim";
    version = "544dd1583f9bb27b393f598475c89809c4d5e86b";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "544dd1583f9bb27b393f598475c89809c4d5e86b";
      fetchSubmodules = false;
      sha256 = "sha256-uNDRynWs7fXDDzDFKvE31oDetv3aabiJfr/r/84z9Sg=";
    };
    date = "2024-07-15";
  };
  neo-tree-nvim = {
    pname = "neo-tree-nvim";
    version = "206241e451c12f78969ff5ae53af45616ffc9b72";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "206241e451c12f78969ff5ae53af45616ffc9b72";
      fetchSubmodules = false;
      sha256 = "sha256-eNGuQEjAKsPuRDGaw95kCVOmP64ZDnUuFBppqtcrhZ4=";
    };
    date = "2024-06-11";
  };
  nui-nvim = {
    pname = "nui-nvim";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-L0ebXtv794357HOAgT17xlEJsmpqIHGqGlYfDB20WTo=";
    };
  };
  nvim-autopairs = {
    pname = "nvim-autopairs";
    version = "e38c5d837e755ce186ae51d2c48e1b387c4425c6";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "e38c5d837e755ce186ae51d2c48e1b387c4425c6";
      fetchSubmodules = false;
      sha256 = "sha256-2+r2SkCtLqKn6CxbEjvUEpsPL5G9KNOf7Q9lGMsolZs=";
    };
    date = "2024-07-23";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "6ac181b5733518040a33017dde654059cd771b7c";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "6ac181b5733518040a33017dde654059cd771b7c";
      fetchSubmodules = false;
      sha256 = "sha256-GRF/6AobXHamw8TZ3FjL7SI6ulcpwpcohsIuZeCSh2A=";
    };
    date = "2024-05-23";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "ae644feb7b67bf1ce4260c231d1d4300b19c6f30";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "ae644feb7b67bf1ce4260c231d1d4300b19c6f30";
      fetchSubmodules = false;
      sha256 = "sha256-NcodgUp8obTsjgc+5j2dKr0f3FelYikQTJngfZXRZzo=";
    };
    date = "2024-08-01";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "v0.1.8";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "v0.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-foJ7a59N0a3QaBW24PtwbyYDQVlIsFxiatADLO/hQvc=";
    };
  };
  nvim-paredit = {
    pname = "nvim-paredit";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "julienvincent";
      repo = "nvim-paredit";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-rls94nrAlPYpHDXp0eB4UzlLRB5HriBuZMdLGVAzGmA=";
    };
  };
  nvim-paredit-scheme = {
    pname = "nvim-paredit-scheme";
    version = "3e5838290dd57116457e4b11eb6ba21e83b260a4";
    src = fetchFromGitHub {
      owner = "ekaitz-zarraga";
      repo = "nvim-paredit-scheme";
      rev = "3e5838290dd57116457e4b11eb6ba21e83b260a4";
      fetchSubmodules = false;
      sha256 = "sha256-gzZJlN8LO1SH0joqgQgGIlkCVreccF8yxRYoinB9tU0=";
    };
    date = "2024-01-27";
  };
  nvim-transparent = {
    pname = "nvim-transparent";
    version = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
    src = fetchFromGitHub {
      owner = "xiyaowong";
      repo = "nvim-transparent";
      rev = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
      fetchSubmodules = false;
      sha256 = "sha256-wT+7rmp08r0XYGp+MhjJX8dsFTar8+nf10CV9OdkOSk=";
    };
    date = "2023-11-13";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "d7353a6b72008b38aa873ace49aa97bea257941b";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "d7353a6b72008b38aa873ace49aa97bea257941b";
      fetchSubmodules = false;
      sha256 = "sha256-ujCFB1dZsJ4Sko151+xxzEpUzQC/GMalKNUr2drLPpQ=";
    };
    date = "2024-08-04";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "3722e3d1fb5fe1896a104eb489e8f8651260b520";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "3722e3d1fb5fe1896a104eb489e8f8651260b520";
      fetchSubmodules = false;
      sha256 = "sha256-TeWMlfNTA5+tiPq6D2TVWjdfJVr3FOwpqUDU8kfFZ8E=";
    };
    date = "2024-08-04";
  };
  org-bullets-nvim = {
    pname = "org-bullets-nvim";
    version = "7e76e04827ac3fb13fc645a6309ac14203c4ca6a";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "org-bullets.nvim";
      rev = "7e76e04827ac3fb13fc645a6309ac14203c4ca6a";
      fetchSubmodules = false;
      sha256 = "sha256-bxiL88uUa0Zd/HL7RcC/XVhbkgdlFr6MmlQfkpxFybE=";
    };
    date = "2024-07-09";
  };
  orgmode = {
    pname = "orgmode";
    version = "0.3.4";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "orgmode";
      rev = "0.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-SmofuYt4fLhtl5qedYlmCRgOmZaw3nmlnMg0OMzyKnM=";
    };
  };
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
      fetchSubmodules = false;
      sha256 = "sha256-5Jf2mWFVDofXBcXLbMa417mqlEPWLA+cQIZH/vNEV1g=";
    };
    date = "2024-05-20";
  };
  telescope-nvim = {
    pname = "telescope-nvim";
    version = "0.1.8";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "0.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-e1ulhc4IIvUgpjKQrSqPY4WpXuez6wlxL6Min9U0o5Q=";
    };
  };
  vim-nix = {
    pname = "vim-nix";
    version = "e25cd0f2e5922f1f4d3cd969f92e35a9a327ffb0";
    src = fetchFromGitHub {
      owner = "LnL7";
      repo = "vim-nix";
      rev = "e25cd0f2e5922f1f4d3cd969f92e35a9a327ffb0";
      fetchSubmodules = false;
      sha256 = "sha256-2/9eyU+uUbcKiNcBDdgdxCBp1vNSP51U/0LTHihEYJY=";
    };
    date = "2024-02-24";
  };
  which-key-nvim = {
    pname = "which-key-nvim";
    version = "v3.13.2";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "v3.13.2";
      fetchSubmodules = false;
      sha256 = "sha256-nv9s4/ax2BoL9IQdk42uN7mxIVFYiTK+1FVvWDKRnGM=";
    };
  };
}
