[plenary-nvim]
src.git = "https://github.com/nvim-lua/plenary.nvim"
fetch.github = "nvim-lua/plenary.nvim"

[nui-nvim]
src.github = "MunifTanjim/nui.nvim"
fetch.github = "MunifTanjim/nui.nvim"

[bufferline-nvim]
fetch.github = "akinsho/bufferline.nvim"
src.github = "akinsho/bufferline.nvim"

[lualine-nvim]
fetch.github = "nvim-lualine/lualine.nvim"
src.git = "https://github.com/nvim-lualine/lualine.nvim"

[nvim-web-devicons]
fetch.github = "nvim-tree/nvim-web-devicons"
src.git = "https://github.com/nvim-tree/nvim-web-devicons"

[nvim-autopairs]
fetch.github = "windwp/nvim-autopairs"
src.git = "https://github.com/windwp/nvim-autopairs"

[neo-tree-nvim]
fetch.github = "nvim-neo-tree/neo-tree.nvim"
src.git = "https://github.com/nvim-neo-tree/neo-tree.nvim"
passthru.opt = "true"

[which-key-nvim]
fetch.github = "folke/which-key.nvim"
src.github = "folke/which-key.nvim"
passthru.opt = "true"

[conform-nvim]
fetch.github = "stevearc/conform.nvim"
src.github = "stevearc/conform.nvim"
passthru.opt = "true"

[telescope-nvim]
fetch.github = "nvim-telescope/telescope.nvim"
src.github = "nvim-telescope/telescope.nvim"
passthru.opt = "true"

[nvim-lspconfig]
fetch.github = "neovim/nvim-lspconfig"
src.github = "neovim/nvim-lspconfig"

[nvim-cmp]
fetch.github = "hrsh7th/nvim-cmp"
src.git = "https://github.com/hrsh7th/nvim-cmp"

[cmp-cmdline]
fetch.github = "hrsh7th/cmp-cmdline"
src.git = "https://github.com/hrsh7th/cmp-cmdline"

[cmp-nvim-lsp]
fetch.github = "hrsh7th/cmp-nvim-lsp"
src.git = "https://github.com/hrsh7th/cmp-nvim-lsp"

[vim-nix]
fetch.github = "LnL7/vim-nix"
src.git = "https://github.com/LnL7/vim-nix"
passthru.opt = "true"

[orgmode]
fetch.github = "nvim-orgmode/orgmode"
src.github = "nvim-orgmode/orgmode"
passthru.opt = "true"

[org-bullets-nvim]
src.git = "https://github.com/nvim-orgmode/org-bullets.nvim"
fetch.github = "nvim-orgmode/org-bullets.nvim"
passthru.opt = "true"

[indent-blankline-nvim]
fetch.github = "lukas-reineke/indent-blankline.nvim"
src.github = "lukas-reineke/indent-blankline.nvim"
passthru.opt = "true"

[neovim-session-manager]
fetch.github = "Shatur/neovim-session-manager"
src.git = "https://github.com/Shatur/neovim-session-manager"
passthru.opt = "true"

[cmp-async-path]
fetch.git = "https://codeberg.org/FelipeLema/cmp-async-path"
src.git = "https://codeberg.org/FelipeLema/cmp-async-path"

[gitsigns-nvim]
fetch.github = "lewis6991/gitsigns.nvim"
src.github = "lewis6991/gitsigns.nvim"
passthru.opt = "true"

[git-conflict-nvim]
fetch.github = "akinsho/git-conflict.nvim"
src.git = "https://github.com/akinsho/git-conflict.nvim"
passthru.opt = "true"

[nvim-dap]
fetch.github = "mfussenegger/nvim-dap"
src.github = "mfussenegger/nvim-dap"
passthru.opt = "true"

[nvim-dap-python]
fetch.github = "mfussenegger/nvim-dap-python"
src.git = "https://github.com/mfussenegger/nvim-dap-python"
passthru.opt = "true"

[telescope-fzf-native-nvim]
fetch.github = "nvim-telescope/telescope-fzf-native.nvim"
src.git = "https://github.com/nvim-telescope/telescope-fzf-native.nvim"
passthru.opt = "true"

[lz-n]
fetch.github = "nvim-neorocks/lz.n"
src.github = "nvim-neorocks/lz.n"

[kaganawa-nvim]
fetch.github = "rebelot/kanagawa.nvim"
src.git = "https://github.com/rebelot/kanagawa.nvim"

[vim-better-whitespace]
fetch.github = "ntpeters/vim-better-whitespace"
src.git = "https://github.com/ntpeters/vim-better-whitespace"
passthru.opt = "true"

[nvim-navic]
fetch.github = "SmiteshP/nvim-navic"
src.git = "https://github.com/SmiteshP/nvim-navic"

[smart-splits-nvim]
fetch.github = "mrjones2014/smart-splits.nvim"
src.github = "mrjones2014/smart-splits.nvim"
passthru.opt = "true"

[nvim-treesitter-textobjects]
fetch.github = "nvim-treesitter/nvim-treesitter-textobjects"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects"
# passthru.opt = "true"

[comment-nvim]
fetch.github = "numToStr/Comment.nvim"
src.git = "https://github.com/numToStr/Comment.nvim"
passthru.opt = "true"

[haskell-tools-nvim]
fetch.github = "mrcjkb/haskell-tools.nvim"
src.github = "mrcjkb/haskell-tools.nvim"

[nvim-ts-autotag]
fetch.github = "windwp/nvim-ts-autotag"
src.git = "https://github.com/windwp/nvim-ts-autotag"

[oil-nvim]
fetch.github = "stevearc/oil.nvim"
src.github = "stevearc/oil.nvim"
passthru.opt = "true"

[mdx-nvim]
fetch.github = "davidmh/mdx.nvim"
src.git = "https://github.com/davidmh/mdx.nvim"

[nvim-treesitter-context]
fetch.github = "nvim-treesitter/nvim-treesitter-context"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter-context"

[noice-nvim]
fetch.github = "folke/noice.nvim"
src.github = "folke/noice.nvim"

[snacks-nvim]
fetch.github = "folke/snacks.nvim"
src.github = "folke/snacks.nvim"

[marks-nvim]
fetch.github = "chentoast/marks.nvim"
src.git = "https://github.com/chentoast/marks.nvim"
passthru.opt = "true"

[trouble-nvim]
fetch.github = "folke/trouble.nvim"
src.github = "folke/trouble.nvim"

[render-markdown-nvim]
fetch.github = "MeanderingProgrammer/render-markdown.nvim"
src.github = "MeanderingProgrammer/render-markdown.nvim"
passthru.opt = "true"

# [avante-nvim]
# fetch.github = "yetone/avante.nvim"
# src.github = "yetone/avante.nvim"
# passthru.opt = "true"

# [blink-cmp]
# fetch.github = "Saghen/blink.cmp"
# src.github = "Saghen/blink.cmp"
