[plenary-nvim]
src.git = "https://github.com/nvim-lua/plenary.nvim"
fetch.github = "nvim-lua/plenary.nvim"

[nui-nvim]
src.github = "MunifTanjim/nui.nvim"
fetch.github = "MunifTanjim/nui.nvim"

[bufferline-nvim]
fetch.github = "akinsho/bufferline.nvim"
src.github = "akinsho/bufferline.nvim"

[lualine-nvim]
fetch.github = "nvim-lualine/lualine.nvim"
src.git = "https://github.com/nvim-lualine/lualine.nvim"

[nvim-web-devicons]
fetch.github = "nvim-tree/nvim-web-devicons"
src.git = "https://github.com/nvim-tree/nvim-web-devicons"

[nvim-autopairs]
fetch.github = "windwp/nvim-autopairs"
src.git = "https://github.com/windwp/nvim-autopairs"

[neo-tree-nvim]
fetch.github = "nvim-neo-tree/neo-tree.nvim"
src.git = "https://github.com/nvim-neo-tree/neo-tree.nvim"
passthru.opt = "true"

# [comment-nvim]
# fetch.github = "numToStr/Comment.nvim"
# src.git = "https://github.com/numToStr/Comment.nvim"

[which-key-nvim]
fetch.github = "folke/which-key.nvim"
src.github = "folke/which-key.nvim"
passthru.opt = "true"

[conform-nvim]
fetch.github = "stevearc/conform.nvim"
src.github = "stevearc/conform.nvim"

[telescope-nvim]
fetch.github = "nvim-telescope/telescope.nvim"
src.github = "nvim-telescope/telescope.nvim"
passthru.opt = "true"

[nvim-lspconfig]
fetch.github = "neovim/nvim-lspconfig"
src.github = "neovim/nvim-lspconfig"

[nvim-cmp]
fetch.github = "hrsh7th/nvim-cmp"
src.git = "https://github.com/hrsh7th/nvim-cmp"

[cmp-cmdline]
fetch.github = "hrsh7th/cmp-cmdline"
src.git = "https://github.com/hrsh7th/cmp-cmdline"

[cmp-nvim-lsp]
fetch.github = "hrsh7th/cmp-nvim-lsp"
src.git = "https://github.com/hrsh7th/cmp-nvim-lsp"

[vim-nix]
fetch.github = "LnL7/vim-nix"
src.git = "https://github.com/LnL7/vim-nix"

# [nvim-transparent]
# fetch.github = "xiyaowong/nvim-transparent"
# src.git = "https://github.com/xiyaowong/nvim-transparent"

# [nvim-base-16]
# fetch.github = "RRethy/nvim-base16"
# src.git = "https://github.com/RRethy/nvim-base16"

[orgmode]
fetch.github = "nvim-orgmode/orgmode"
src.github = "nvim-orgmode/orgmode"

[org-bullets-nvim]
src.git = "https://github.com/nvim-orgmode/org-bullets.nvim"
fetch.github = "nvim-orgmode/org-bullets.nvim"

[nvim-paredit-scheme]
src.git = "https://github.com/ekaitz-zarraga/nvim-paredit-scheme"
fetch.github = "ekaitz-zarraga/nvim-paredit-scheme"

[nvim-paredit]
src.github = "julienvincent/nvim-paredit"
fetch.github = "julienvincent/nvim-paredit"

[guess-indent-nvim]
fetch.github = "NMAC427/guess-indent.nvim"
src.git = "https://github.com/NMAC427/guess-indent.nvim"

[indent-blankline-nvim]
fetch.github = "lukas-reineke/indent-blankline.nvim"
src.github = "lukas-reineke/indent-blankline.nvim"

[neovim-session-manager]
fetch.github = "Shatur/neovim-session-manager"
src.git = "https://github.com/Shatur/neovim-session-manager"

[cmp-async-path]
fetch.git = "https://codeberg.org/FelipeLema/cmp-async-path"
src.git = "https://codeberg.org/FelipeLema/cmp-async-path"

[gitsigns-nvim]
fetch.github = "lewis6991/gitsigns.nvim"
src.github = "lewis6991/gitsigns.nvim"
passthru.opt = "true"

[git-conflict-nvim]
fetch.github = "akinsho/git-conflict.nvim"
src.git = "https://github.com/akinsho/git-conflict.nvim"

[fidget-nvim]
fetch.github = "j-hui/fidget.nvim"
src.git = "https://github.com/j-hui/fidget.nvim"

[nvim-dap]
fetch.github = "mfussenegger/nvim-dap"
src.github = "mfussenegger/nvim-dap"
passthru.opt = "true"

[nvim-dap-python]
fetch.github = "mfussenegger/nvim-dap-python"
src.git = "https://github.com/mfussenegger/nvim-dap-python"
passthru.opt = "true"

[telescope-fzf-native-nvim]
fetch.github = "nvim-telescope/telescope-fzf-native.nvim"
src.git = "https://github.com/nvim-telescope/telescope-fzf-native.nvim"
passthru.opt = "true"

[lz-n]
fetch.github = "nvim-neorocks/lz.n"
src.github = "nvim-neorocks/lz.n"
