[plenary-nvim]
src.git = "https://github.com/nvim-lua/plenary.nvim"
fetch.github = "nvim-lua/plenary.nvim"

[nui-nvim]
src.github = "MunifTanjim/nui.nvim"
fetch.github = "MunifTanjim/nui.nvim"

[nvim-treesitter]
fetch.github = "nvim-treesitter/nvim-treesitter"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter"

[bufferline-nvim]
fetch.github = "akinsho/bufferline.nvim"
src.github = "akinsho/bufferline.nvim"

[lualine-nvim]
fetch.github = "nvim-lualine/lualine.nvim"
src.git = "https://github.com/nvim-lualine/lualine.nvim"

[nvim-web-devicons]
fetch.github = "nvim-tree/nvim-web-devicons"
src.git = "https://github.com/nvim-tree/nvim-web-devicons"

[nvim-autopairs]
fetch.github = "windwp/nvim-autopairs"
src.git = "https://github.com/windwp/nvim-autopairs"

[neo-tree-nvim]
fetch.github = "nvim-neo-tree/neo-tree.nvim"
src.git = "https://github.com/nvim-neo-tree/neo-tree.nvim"

[comment-nvim]
fetch.github = "numToStr/Comment.nvim"
src.git = "https://github.com/numToStr/Comment.nvim"

[which-key-nvim]
fetch.github = "folke/which-key.nvim"
src.github = "folke/which-key.nvim"

[conform-nvim]
fetch.github = "stevearc/conform.nvim"
src.github = "stevearc/conform.nvim"

[telescope-nvim]
fetch.github = "nvim-telescope/telescope.nvim"
src.github = "nvim-telescope/telescope.nvim"

[nvim-lspconfig]
fetch.github = "neovim/nvim-lspconfig"
src.github = "neovim/nvim-lspconfig"

[nvim-cmp]
fetch.github = "hrsh7th/nvim-cmp"
src.git = "https://github.com/hrsh7th/nvim-cmp"

[cmp-cmdline]
fetch.github = "hrsh7th/cmp-cmdline"
src.git = "https://github.com/hrsh7th/cmp-cmdline"

[cmp-nvim-lsp]
fetch.github = "hrsh7th/cmp-nvim-lsp"
src.git = "https://github.com/hrsh7th/cmp-nvim-lsp"

[cmp-buffer]
fetch.github = "hrsh7th/cmp-buffer"
src.git = "https://github.com/hrsh7th/cmp-buffer"

[cmp-path]
fetch.github = "hrsh7th/cmp-path"
src.git = "https://github.com/hrsh7th/cmp-path"

[vim-nix]
fetch.github = "LnL7/vim-nix"
src.git = "https://github.com/LnL7/vim-nix"

[nvim-transparent]
fetch.github = "xiyaowong/nvim-transparent"
src.git = "https://github.com/xiyaowong/nvim-transparent"

[nvim-base-16]
fetch.github = "RRethy/nvim-base16"
src.git = "https://github.com/RRethy/nvim-base16"

[orgmode]
fetch.github = "nvim-orgmode/orgmode"
src.github = "nvim-orgmode/orgmode"

[org-bullets-nvim]
src.git = "https://github.com/nvim-orgmode/org-bullets.nvim"
fetch.github = "nvim-orgmode/org-bullets.nvim"

[nvim-paredit-scheme]
src.git = "https://github.com/ekaitz-zarraga/nvim-paredit-scheme"
fetch.github = "ekaitz-zarraga/nvim-paredit-scheme"

[nvim-paredit]
src.github = "julienvincent/nvim-paredit"
fetch.github = "julienvincent/nvim-paredit"
