# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  blink-cmp = {
    pname = "blink-cmp";
    version = "v0.12.4";
    src = fetchFromGitHub {
      owner = "Saghen";
      repo = "blink.cmp";
      rev = "v0.12.4";
      fetchSubmodules = false;
      sha256 = "sha256-ybzEQHvZIiF+B2SIdFX8HJGai50PUw5QRgrL7qJ0sUk=";
    };
  };
  bufferline-nvim = {
    pname = "bufferline-nvim";
    version = "v4.9.1";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "v4.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-ae4MB6+6v3awvfSUWlau9ASJ147ZpwuX1fvJdfMwo1Q=";
    };
  };
  cmp-async-path = {
    pname = "cmp-async-path";
    version = "d6d1ffa2075039632a2d71e8fa139818e15ac757";
    src = fetchgit {
      url = "https://codeberg.org/FelipeLema/cmp-async-path";
      rev = "d6d1ffa2075039632a2d71e8fa139818e15ac757";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MZFpNPtSDMZNkfoz+3ZcDxLb8PvDtm9nb1dE0CbYIPQ=";
    };
    date = "2024-10-21";
  };
  cmp-cmdline = {
    pname = "cmp-cmdline";
    version = "d250c63aa13ead745e3a40f61fdd3470efde3923";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "d250c63aa13ead745e3a40f61fdd3470efde3923";
      fetchSubmodules = false;
      sha256 = "sha256-iBmXp+gUSMbgfkv7c7RDQAwPq02e07wEnBETP0dWBOo=";
    };
    date = "2024-03-22";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "99290b3ec1322070bcfb9e846450a46f6efa50f0";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "99290b3ec1322070bcfb9e846450a46f6efa50f0";
      fetchSubmodules = false;
      sha256 = "sha256-iaihXNCF5bB5MdeoosD/kc3QtpA/QaIDZVLiLIurBSM=";
    };
    date = "2024-12-10";
  };
  comment-nvim = {
    pname = "comment-nvim";
    version = "e30b7f2008e52442154b66f7c519bfd2f1e32acb";
    src = fetchFromGitHub {
      owner = "numToStr";
      repo = "Comment.nvim";
      rev = "e30b7f2008e52442154b66f7c519bfd2f1e32acb";
      fetchSubmodules = false;
      sha256 = "sha256-h0kPue5Eqd5aeu4VoLH45pF0DmWWo1d8SnLICSQ63zc=";
    };
    opt = "true";
    date = "2024-06-09";
  };
  conform-nvim = {
    pname = "conform-nvim";
    version = "v9.0.0";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "conform.nvim";
      rev = "v9.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-H9JLiRtixDKDN50SH6gkqgjlhLzHMAaOT1pc69ZFdco=";
    };
    opt = "true";
  };
  git-conflict-nvim = {
    pname = "git-conflict-nvim";
    version = "a1badcd070d176172940eb55d9d59029dad1c5a6";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "git-conflict.nvim";
      rev = "a1badcd070d176172940eb55d9d59029dad1c5a6";
      fetchSubmodules = false;
      sha256 = "sha256-CmSgmpg5K3ySXYrDjg8yTAojeLWJdSHP8uNVFyrkNhc=";
    };
    opt = "true";
    date = "2024-12-27";
  };
  gitsigns-nvim = {
    pname = "gitsigns-nvim";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-C7ScLPhxpr/GB3YYpLr4mEoAR02f4eeeFW5nJniMBtc=";
    };
    opt = "true";
  };
  haskell-tools-nvim = {
    pname = "haskell-tools-nvim";
    version = "v4.4.2";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "haskell-tools.nvim";
      rev = "v4.4.2";
      fetchSubmodules = false;
      sha256 = "sha256-2YxqkH+b5vTF+YM6cIlYKHtVCjP7i2OZbQK2LpQYMOQ=";
    };
  };
  indent-blankline-nvim = {
    pname = "indent-blankline-nvim";
    version = "v3.8.7";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "v3.8.7";
      fetchSubmodules = false;
      sha256 = "sha256-Y1WP3wDj2MFgqW1ssUro9enLZS+OM3XViv3j/4+5rrc=";
    };
    opt = "true";
  };
  kaganawa-nvim = {
    pname = "kaganawa-nvim";
    version = "2de175482f215c69a1d12ab10a8bf2a7a2e44ff2";
    src = fetchFromGitHub {
      owner = "rebelot";
      repo = "kanagawa.nvim";
      rev = "2de175482f215c69a1d12ab10a8bf2a7a2e44ff2";
      fetchSubmodules = false;
      sha256 = "sha256-5ee5TqTcCA+2F0zrshhbDvrrTkZ0dQYzhqq+t5KnTpI=";
    };
    date = "2025-02-14";
  };
  lualine-nvim = {
    pname = "lualine-nvim";
    version = "f4f791f67e70d378a754d02da068231d2352e5bc";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "f4f791f67e70d378a754d02da068231d2352e5bc";
      fetchSubmodules = false;
      sha256 = "sha256-uAxe3UdNUVfdpQcKvGvQ/E2blGksvMPlTBfEOtgeVYo=";
    };
    date = "2025-02-08";
  };
  lz-n = {
    pname = "lz-n";
    version = "v2.11.2";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "v2.11.2";
      fetchSubmodules = false;
      sha256 = "sha256-40ikpJGivib7waDGJVKDZuWcGi5BETKrdDy6gQAOmCw=";
    };
  };
  marks-nvim = {
    pname = "marks-nvim";
    version = "bb25ae3f65f504379e3d08c8a02560b76eaf91e8";
    src = fetchFromGitHub {
      owner = "chentoast";
      repo = "marks.nvim";
      rev = "bb25ae3f65f504379e3d08c8a02560b76eaf91e8";
      fetchSubmodules = false;
      sha256 = "sha256-1X2hkvVhYl2S/sAQyJ1JPVTy33xs3iHcMUofomXhwkE=";
    };
    opt = "true";
    date = "2024-09-02";
  };
  mdx-nvim = {
    pname = "mdx-nvim";
    version = "464a74be368dce212cff02f6305845dc7f209ab3";
    src = fetchFromGitHub {
      owner = "davidmh";
      repo = "mdx.nvim";
      rev = "464a74be368dce212cff02f6305845dc7f209ab3";
      fetchSubmodules = false;
      sha256 = "sha256-jpMcrWx/Rg9sMfkQFXnIM8VB5qRuSB/70wuSh6Y5uFk=";
    };
    date = "2025-01-04";
  };
  neo-tree-nvim = {
    pname = "neo-tree-nvim";
    version = "94c8ec36da52af0ea0128012e12abe05c26ef840";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "94c8ec36da52af0ea0128012e12abe05c26ef840";
      fetchSubmodules = false;
      sha256 = "sha256-IgEW55fwV3prifCng4R3QtWF3HN8pycVNN5U5ZCPI7E=";
    };
    opt = "true";
    date = "2025-02-20";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "270e235b014f0c37bf362eb1e8913d66bba33a2e";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "270e235b014f0c37bf362eb1e8913d66bba33a2e";
      fetchSubmodules = false;
      sha256 = "sha256-0CB7/hqj3zEZPQUOQoaETcNzFJcQyKt3k7hIXoArhZg=";
    };
    opt = "true";
    date = "2025-01-19";
  };
  noice-nvim = {
    pname = "noice-nvim";
    version = "v4.10.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "noice.nvim";
      rev = "v4.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-gq3S/RZw7ojVldNUtQPsgMA0EyHGVzt/JcOojlHrOSQ=";
    };
  };
  nui-nvim = {
    pname = "nui-nvim";
    version = "0.3.0";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-L0ebXtv794357HOAgT17xlEJsmpqIHGqGlYfDB20WTo=";
    };
  };
  nvim-autopairs = {
    pname = "nvim-autopairs";
    version = "68f0e5c3dab23261a945272032ee6700af86227a";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "68f0e5c3dab23261a945272032ee6700af86227a";
      fetchSubmodules = false;
      sha256 = "sha256-FUnYZWSJh5wAfXevH+nK+g/s4WhnzwxbW6a3gUDQI6o=";
    };
    date = "2025-02-14";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "12509903a5723a876abd65953109f926f4634c30";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "12509903a5723a876abd65953109f926f4634c30";
      fetchSubmodules = false;
      sha256 = "sha256-a45FPHLtM1AnBlvJZ/ka5m7gOz84rpVk8GH75fYWqSg=";
    };
    date = "2025-01-23";
  };
  nvim-dap = {
    pname = "nvim-dap";
    version = "0.9.0";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-evpP8qAtNuEL1EVUVoCB+PQ1Mmn08FJuufkwnOT+oTg=";
    };
    opt = "true";
  };
  nvim-dap-python = {
    pname = "nvim-dap-python";
    version = "34282820bb713b9a5fdb120ae8dd85c2b3f49b51";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "34282820bb713b9a5fdb120ae8dd85c2b3f49b51";
      fetchSubmodules = false;
      sha256 = "sha256-Qz0eZGVy/3q2qBtyliw1bxiJE9NT02F1hZoVNm3KU5g=";
    };
    opt = "true";
    date = "2024-11-29";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "v1.6.0";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "v1.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-wXe1cUnsiOLegeYvL2Tvn4H3p9/b9Qi9rDzX+jjhZ+Q=";
    };
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "8649f694d3e76ee10c19255dece6411c29206a54";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "8649f694d3e76ee10c19255dece6411c29206a54";
      fetchSubmodules = false;
      sha256 = "sha256-0p5n/V8Jlj9XyxV/fuMwsbQ7oV5m9H2GqZZEA/njxCQ=";
    };
    date = "2023-11-30";
  };
  nvim-treesitter-context = {
    pname = "nvim-treesitter-context";
    version = "198720b4016af04c9590f375d714d5bf8afecc1a";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-context";
      rev = "198720b4016af04c9590f375d714d5bf8afecc1a";
      fetchSubmodules = false;
      sha256 = "sha256-MSfSbepp+sA0GHz2StzgcQgWMhd04fmW9swmUGLiuo4=";
    };
    date = "2025-02-17";
  };
  nvim-treesitter-textobjects = {
    pname = "nvim-treesitter-textobjects";
    version = "ad8f0a472148c3e0ae9851e26a722ee4e29b1595";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "ad8f0a472148c3e0ae9851e26a722ee4e29b1595";
      fetchSubmodules = false;
      sha256 = "sha256-b/7Bz7L83KL+uZC1bRJ4PrzPVK/NaCKSx4VCHlPcdCM=";
    };
    date = "2024-11-22";
  };
  nvim-ts-autotag = {
    pname = "nvim-ts-autotag";
    version = "a1d526af391f6aebb25a8795cbc05351ed3620b5";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "a1d526af391f6aebb25a8795cbc05351ed3620b5";
      fetchSubmodules = false;
      sha256 = "sha256-a3Bcql68mp3y5bH9XMiDTQB0e75T+qFB593objIGg/I=";
    };
    date = "2025-02-18";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "1020869742ecb191f260818234517f4a1515cfe8";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "1020869742ecb191f260818234517f4a1515cfe8";
      fetchSubmodules = false;
      sha256 = "sha256-WOFtHvNlPP1JRLdCfFRXEOUx+1z5d5ncm+pS0wpDjAg=";
    };
    date = "2025-02-11";
  };
  oil-nvim = {
    pname = "oil-nvim";
    version = "v2.15.0";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "oil.nvim";
      rev = "v2.15.0";
      fetchSubmodules = false;
      sha256 = "sha256-jCuOwTd6QIy3USuE7X/rHYUbriW6+2WaK9JxCx4/O2c=";
    };
    opt = "true";
  };
  org-bullets-nvim = {
    pname = "org-bullets-nvim";
    version = "21437cfa99c70f2c18977bffd423f912a7b832ea";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "org-bullets.nvim";
      rev = "21437cfa99c70f2c18977bffd423f912a7b832ea";
      fetchSubmodules = false;
      sha256 = "sha256-/l8IfvVSPK7pt3Or39+uenryTM5aBvyJZX5trKNh0X0=";
    };
    opt = "true";
    date = "2025-01-23";
  };
  orgmode = {
    pname = "orgmode";
    version = "0.4.31";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "orgmode";
      rev = "0.4.31";
      fetchSubmodules = false;
      sha256 = "sha256-Al1A9D8wO0SS0AXIyhLeNBPoWA8oxJ7jjAl23Qt2BVM=";
    };
    opt = "true";
  };
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "857c5ac632080dba10aae49dba902ce3abf91b35";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "857c5ac632080dba10aae49dba902ce3abf91b35";
      fetchSubmodules = false;
      sha256 = "sha256-8FV5RjF7QbDmQOQynpK7uRKONKbPRYbOPugf9ZxNvUs=";
    };
    date = "2025-02-11";
  };
  render-markdown-nvim = {
    pname = "render-markdown-nvim";
    version = "v8.0.0";
    src = fetchFromGitHub {
      owner = "MeanderingProgrammer";
      repo = "render-markdown.nvim";
      rev = "v8.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-1GbjWHfcC6TIQM1zPnybKs0fcNbQjJJcb6Rb4R9T3nc=";
    };
    opt = "true";
  };
  smart-splits-nvim = {
    pname = "smart-splits-nvim";
    version = "v1.8.1";
    src = fetchFromGitHub {
      owner = "mrjones2014";
      repo = "smart-splits.nvim";
      rev = "v1.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-5dclrvSTF3Eg/aQ5FaTVqW+i9h0YRcJlwBCofPaY+Qs=";
    };
    opt = "true";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "v2.21.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "v2.21.0";
      fetchSubmodules = false;
      sha256 = "sha256-COvKNofUMiNV9MZvP18dtmkNSMXeTlumN2sIeBl4VqE=";
    };
  };
  telescope-fzf-native-nvim = {
    pname = "telescope-fzf-native-nvim";
    version = "2a5ceff981501cff8f46871d5402cd3378a8ab6a";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-fzf-native.nvim";
      rev = "2a5ceff981501cff8f46871d5402cd3378a8ab6a";
      fetchSubmodules = false;
      sha256 = "sha256-0dGvpN8Vn+aU6j8N0tTD8AOzOAHGemlPAcLKyqlWvlg=";
    };
    opt = "true";
    date = "2025-02-11";
  };
  telescope-nvim = {
    pname = "telescope-nvim";
    version = "0.1.8";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "0.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-e1ulhc4IIvUgpjKQrSqPY4WpXuez6wlxL6Min9U0o5Q=";
    };
    opt = "true";
  };
  trouble-nvim = {
    pname = "trouble-nvim";
    version = "v3.7.1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "v3.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-F3LSA1iAF8TEI7ecyuWVe3FrpSddUf3OjJA/KGfdW/8=";
    };
  };
  vim-better-whitespace = {
    pname = "vim-better-whitespace";
    version = "86a0579b330b133b8181b8e088943e81c26a809e";
    src = fetchFromGitHub {
      owner = "ntpeters";
      repo = "vim-better-whitespace";
      rev = "86a0579b330b133b8181b8e088943e81c26a809e";
      fetchSubmodules = false;
      sha256 = "sha256-muYPVkTXSur2+/3L/bCB2rlwNl98TI+9WGfIANU+4aQ=";
    };
    opt = "true";
    date = "2024-06-12";
  };
  vim-nix = {
    pname = "vim-nix";
    version = "7235c7ce2cea530cb6b59bc3e46d4bfe917d15c8";
    src = fetchFromGitHub {
      owner = "LnL7";
      repo = "vim-nix";
      rev = "7235c7ce2cea530cb6b59bc3e46d4bfe917d15c8";
      fetchSubmodules = false;
      sha256 = "sha256-Hmn8EVlvMQnQF8COeb89cgl5+A83kagOjGsmvm5WNoE=";
    };
    opt = "true";
    date = "2025-02-01";
  };
  which-key-nvim = {
    pname = "which-key-nvim";
    version = "v3.16.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "v3.16.0";
      fetchSubmodules = false;
      sha256 = "sha256-CNnRQjGLOH+Ol+cVgnfpKbJByD3kLPGAbKefvnHjzRg=";
    };
    opt = "true";
  };
}
