# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  iosevka = {
    pname = "iosevka";
    version = "v1.3.2";
    src = fetchurl {
      url = "https://github.com/viperML/iosevka/releases/download/v1.3.2/iosevka-ttf-nerd-zip.zip";
      sha256 = "sha256-TizKUzNYwKGeW4ThmEA5zYjui1smcZYKiCcHFDyngCE=";
    };
  };
}
