# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  sierrabreezeenhanced = {
    pname = "sierrabreezeenhanced";
    version = "7151f4d8eacb686a9ce6545677c07996f6bdc141";
    src = fetchFromGitHub ({
      owner = "kupiqu";
      repo = "SierraBreezeEnhanced";
      rev = "7151f4d8eacb686a9ce6545677c07996f6bdc141";
      fetchSubmodules = false;
      sha256 = "sha256-zTUTsSzy4p0Y7RPOidCtxTjjyvPRyWSQCxA5sUzXcLc=";
    });
    date = "2023-03-21";
  };
}
