# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  sierrabreezeenhanced = {
    pname = "sierrabreezeenhanced";
    version = "9840f80b6b7992cf7b3b47f9feba207e26253616";
    src = fetchFromGitHub {
      owner = "kupiqu";
      repo = "SierraBreezeEnhanced";
      rev = "9840f80b6b7992cf7b3b47f9feba207e26253616";
      fetchSubmodules = false;
      sha256 = "sha256-FkYmmqUjsegoEuZhqO2E048nFDei4DbDgw+s37x2/JQ=";
    };
    date = "2023-06-13";
  };
}
