# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  sierrabreezeenhanced = {
    pname = "sierrabreezeenhanced";
    version = "fb8e1652f8058956610d6783deb5d4ab6ba73cb4";
    src = fetchFromGitHub ({
      owner = "kupiqu";
      repo = "SierraBreezeEnhanced";
      rev = "fb8e1652f8058956610d6783deb5d4ab6ba73cb4";
      fetchSubmodules = false;
      sha256 = "sha256-x3OTLH8gcWrqpFGQPZHwvyPFwLhEGeHhU4cRqvtPupQ=";
    });
  };
}
