# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  resolve-march-native = {
    pname = "resolve-march-native";
    version = "2f786d47394eb9d3ac139df118920f4fde062c69";
    src = fetchFromGitHub ({
      owner = "hartwork";
      repo = "resolve-march-native";
      rev = "2f786d47394eb9d3ac139df118920f4fde062c69";
      fetchSubmodules = false;
      sha256 = "sha256-VZBIfsczbbkrV/njhc5pbOsU/gmE+cuLgsA0ii0BHfk=";
    });
    date = "2023-03-20";
  };
}
