# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  resolve-march-native = {
    pname = "resolve-march-native";
    version = "dd852035df27ec40321136898ff90788f0b3c924";
    src = fetchFromGitHub ({
      owner = "hartwork";
      repo = "resolve-march-native";
      rev = "dd852035df27ec40321136898ff90788f0b3c924";
      fetchSubmodules = false;
      sha256 = "sha256-D9e7ct3jCO9xEjLSwTgRJ99P6fSKlaloT/YzhFXrIA8=";
    });
    date = "2023-01-09";
  };
}
