# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  resolve-march-native = {
    pname = "resolve-march-native";
    version = "56749d04d395cc5979858e22e66b7c2610d5a86f";
    src = fetchFromGitHub ({
      owner = "hartwork";
      repo = "resolve-march-native";
      rev = "56749d04d395cc5979858e22e66b7c2610d5a86f";
      fetchSubmodules = false;
      sha256 = "sha256-vJzkVL23fvFO1pGJwdPiqR73K9iNJ6OglVxL5tCVa2U=";
    });
    date = "2023-03-20";
  };
}
