# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  adw-gtk3 = {
    pname = "adw-gtk3";
    version = "v3.4";
    src = fetchFromGitHub ({
      owner = "lassekongo83";
      repo = "adw-gtk3";
      rev = "v3.4";
      fetchSubmodules = false;
      sha256 = "sha256-hDaEqiUq4vs8Rrv7iCkH2ul+5wuElRzgNJQW8LK1wxU=";
    });
  };
}
