# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  adw-gtk3 = {
    pname = "adw-gtk3";
    version = "v4.7";
    src = fetchFromGitHub ({
      owner = "lassekongo83";
      repo = "adw-gtk3";
      rev = "v4.7";
      fetchSubmodules = false;
      sha256 = "sha256-AJhavwxa0l1JoBrw7v+SM+1wMwhTTHL4LOyMWtHjzqg=";
    });
  };
}
