# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  awesome = {
    pname = "awesome";
    version = "963622af8e6cc718ab4be4799c1599107b610387";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "963622af8e6cc718ab4be4799c1599107b610387";
      fetchSubmodules = false;
      sha256 = "sha256-aEqTync23f94QfiXtf9kU8EKVVFv1HpgpWfPWh8n1BE=";
    });
    date = "2022-10-10";
  };
}
