# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  awesome = {
    pname = "awesome";
    version = "1239cdf4bc9208f57e4bf018d462c2ee63bf0387";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "1239cdf4bc9208f57e4bf018d462c2ee63bf0387";
      fetchSubmodules = false;
      sha256 = "sha256-iAazEbkFOP6FyeUd4tXTQzPosqmNM0Mxf1c1m/eRKWs=";
    });
    date = "2022-12-09";
  };
}
