# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  awesome = {
    pname = "awesome";
    version = "b6263bf209dc69482ddbf10987e1f71577bc98cb";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "b6263bf209dc69482ddbf10987e1f71577bc98cb";
      fetchSubmodules = false;
      sha256 = "sha256-+bd9e2GDKwt71H1m6QbyMP8kDBRDxAJ9eK+5TerMSfQ=";
    });
    date = "2023-04-23";
  };
}
