# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bismuth = {
    pname = "bismuth";
    version = "ef69afe69f615149ab347e4402862ee900452a65";
    src = fetchFromGitHub ({
      owner = "Bismuth-Forge";
      repo = "bismuth";
      rev = "ef69afe69f615149ab347e4402862ee900452a65";
      fetchSubmodules = false;
      sha256 = "sha256-W958M0DxBhXpAKLSjmimppEfOuqj/9/1aMAayTKeENU=";
    });
    date = "2022-12-22";
  };
}
