# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  multiload-ng = {
    pname = "multiload-ng";
    version = "743885da84474bfffc5f5505c0d1a7160de6afef";
    src = fetchFromGitHub {
      owner = "udda";
      repo = "multiload-ng";
      rev = "743885da84474bfffc5f5505c0d1a7160de6afef";
      fetchSubmodules = false;
      sha256 = "sha256-AMjbNXK0NeRz7cfzn7kCkY6zllrVXBqB44FMics5xOw=";
    };
    date = "2021-01-03";
  };
}
