# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  doomemacs = {
    pname = "doomemacs";
    version = "a2484538b48237636a70e5b4ccd358a4fb03c13c";
    src = fetchFromGitHub {
      owner = "doomemacs";
      repo = "doomemacs";
      rev = "a2484538b48237636a70e5b4ccd358a4fb03c13c";
      fetchSubmodules = false;
      sha256 = "sha256-j/wzFY+ll6F6K5Tom2zgdUPqbq5OrHnAOXnL6cr4Ex0=";
    };
    date = "2024-02-07";
  };
}
