[font]
normal = { family = "iosevka-normal", style = "Medium" }
size = 14

[terminal]
shell = { program = "zellij" }
osc52 = "CopyPaste"

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x121212'
foreground = '0xc5c8c6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d1f21'
cursor = '0xc5c8c6'

# Normal colors
[colors.normal]
black = '0x1d1f21'
red = '0xcc6666'
green = '0xb5bd68'
yellow = '0xf0c674'
blue = '0x81a2be'
magenta = '0xb294bb'
cyan = '0x8abeb7'
white = '0xc5c8c6'

# Bright colors
[colors.bright]
black = '0x969896'
red = '0xde935f'
green = '0x282a2e'
yellow = '0x373b41'
blue = '0xb4b7b4'
magenta = '0xe0e0e0'
cyan = '0xa3685a'
white = '0xffffff'

