# Default colors
[colors.primary]
background = '0x1D1D1D'
foreground = '0xc5c8c6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1d1f21'
cursor = '0xc5c8c6'

# Normal colors
[colors.normal]
black = '0x1d1f21'
red = '0xcc6666'
green = '0xb5bd68'
yellow = '0xf0c674'
blue = '0x81a2be'
magenta = '0xb294bb'
cyan = '0x8abeb7'
white = '0xc5c8c6'

# Bright colors
[colors.bright]
black = '0x696969'
red = '0xCC6666'
green = '0xB5BD68'
yellow = '0xF0C674'
blue = '0x81A2BE'
magenta = '0xB294BB'
cyan = '0x8ABEB7'
white = '0xFFFFFF'

