# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  awesome-wm-widgets = {
    pname = "awesome-wm-widgets";
    version = "3bb3d56c26ac3500aab33381af0cccebf6aaa05c";
    src = fetchFromGitHub ({
      owner = "streetturtle";
      repo = "awesome-wm-widgets";
      rev = "3bb3d56c26ac3500aab33381af0cccebf6aaa05c";
      fetchSubmodules = false;
      sha256 = "sha256-zXAiEeAJibdmF5lpSJc7zZrgUJP/+l/dKcBR1HdUf9k=";
    });
    date = "2022-09-02";
  };
  bling = {
    pname = "bling";
    version = "e6de047ced41051236a390b081105f598cb0ad8b";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "e6de047ced41051236a390b081105f598cb0ad8b";
      fetchSubmodules = false;
      sha256 = "sha256-ehFUAhLUEOfqB/2Dung7fBPTCvuXepZB6oVLUv+rkTk=";
    });
    date = "2022-11-20";
  };
  freedesktop = {
    pname = "freedesktop";
    version = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
    src = fetchFromGitHub ({
      owner = "lcpz";
      repo = "awesome-freedesktop";
      rev = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
      fetchSubmodules = false;
      sha256 = "sha256-lQstCcTPUYUt5hzAJIyQ16crPngeOnUla7I4QiG6gEs=";
    });
    date = "2022-06-23";
  };
  lain = {
    pname = "lain";
    version = "88f5a8abd2649b348ffec433a24a263b37f122c0";
    src = fetchFromGitHub ({
      owner = "lcpz";
      repo = "lain";
      rev = "88f5a8abd2649b348ffec433a24a263b37f122c0";
      fetchSubmodules = false;
      sha256 = "sha256-MH/aiYfcO3lrcuNbnIu4QHqPq25LwzTprOhEJUJBJ7I=";
    });
    date = "2023-01-12";
  };
  revelation = {
    pname = "revelation";
    version = "d8b58e3776ec0ace45b5bc1160e322b69fa16d6f";
    src = fetchFromGitHub ({
      owner = "guotsuan";
      repo = "awesome-revelation";
      rev = "d8b58e3776ec0ace45b5bc1160e322b69fa16d6f";
      fetchSubmodules = false;
      sha256 = "sha256-YwIQxjKJFgJdCwPs1Vq7JrmmdN3PVxLKofVOiWQZu7Y=";
    });
    date = "2020-08-07";
  };
  sharedtags = {
    pname = "sharedtags";
    version = "47fbce14337600124d49d33eb2476b5ed96a966c";
    src = fetchFromGitHub ({
      owner = "Drauthius";
      repo = "awesome-sharedtags";
      rev = "47fbce14337600124d49d33eb2476b5ed96a966c";
      fetchSubmodules = false;
      sha256 = "sha256-7YqRMiqIOhyorug2ju1XrSB3b+qne6fIpy8RuHbQTZc=";
    });
    date = "2023-01-14";
  };
}
