# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  awesome-wm-widgets = {
    pname = "awesome-wm-widgets";
    version = "5358c40a029252c1bfcabb4132e05621934a2cf6";
    src = fetchFromGitHub ({
      owner = "streetturtle";
      repo = "awesome-wm-widgets";
      rev = "5358c40a029252c1bfcabb4132e05621934a2cf6";
      fetchSubmodules = false;
      sha256 = "sha256-3pTAErLSrN8sDc/45fNxNqZdL0td+1rn3C9SOPgafSk=";
    });
  };
  bling = {
    pname = "bling";
    version = "70c894e58bb88dea55e9799ad373fdaea309da9e";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "70c894e58bb88dea55e9799ad373fdaea309da9e";
      fetchSubmodules = false;
      sha256 = "sha256-sUUMgdAmXAB/2ocwoo2OTZlWRbSRLdKi1oZB20qRNWU=";
    });
  };
  freedesktop = {
    pname = "freedesktop";
    version = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
    src = fetchFromGitHub ({
      owner = "lcpz";
      repo = "awesome-freedesktop";
      rev = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
      fetchSubmodules = false;
      sha256 = "sha256-lQstCcTPUYUt5hzAJIyQ16crPngeOnUla7I4QiG6gEs=";
    });
  };
  lain = {
    pname = "lain";
    version = "c489aa63acc1364851e0e51152be3db5c75e145d";
    src = fetchFromGitHub ({
      owner = "lcpz";
      repo = "lain";
      rev = "c489aa63acc1364851e0e51152be3db5c75e145d";
      fetchSubmodules = false;
      sha256 = "sha256-s80jruDrLoR5lN+FkfwWf8jb7MtlIJWo7gT8TeVZgtc=";
    });
  };
  revelation = {
    pname = "revelation";
    version = "d8b58e3776ec0ace45b5bc1160e322b69fa16d6f";
    src = fetchFromGitHub ({
      owner = "guotsuan";
      repo = "awesome-revelation";
      rev = "d8b58e3776ec0ace45b5bc1160e322b69fa16d6f";
      fetchSubmodules = false;
      sha256 = "sha256-YwIQxjKJFgJdCwPs1Vq7JrmmdN3PVxLKofVOiWQZu7Y=";
    });
  };
  sharedtags = {
    pname = "sharedtags";
    version = "2a4396ea777de75258777948a93389714206bd93";
    src = fetchFromGitHub ({
      owner = "Drauthius";
      repo = "awesome-sharedtags";
      rev = "2a4396ea777de75258777948a93389714206bd93";
      fetchSubmodules = false;
      sha256 = "sha256-YTDKuUqUanh4AWOyEQUKjf3LwkicEuS1gJIVOg6U8iE=";
    });
  };
}
