# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  awesome-wm-widgets = {
    pname = "awesome-wm-widgets";
    version = "3bb3d56c26ac3500aab33381af0cccebf6aaa05c";
    src = fetchFromGitHub ({
      owner = "streetturtle";
      repo = "awesome-wm-widgets";
      rev = "3bb3d56c26ac3500aab33381af0cccebf6aaa05c";
      fetchSubmodules = false;
      sha256 = "sha256-zXAiEeAJibdmF5lpSJc7zZrgUJP/+l/dKcBR1HdUf9k=";
    });
    date = "2022-09-02";
  };
  bling = {
    pname = "bling";
    version = "5995a7f4b1850c66f9f7848c62c9e120b2079d87";
    src = fetchFromGitHub ({
      owner = "BlingCorp";
      repo = "bling";
      rev = "5995a7f4b1850c66f9f7848c62c9e120b2079d87";
      fetchSubmodules = false;
      sha256 = "sha256-EZ4J+/lp01O9//nh7QCSN76CzZBsyYKZhYnuZ/e3RYo=";
    });
    date = "2022-11-05";
  };
  freedesktop = {
    pname = "freedesktop";
    version = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
    src = fetchFromGitHub ({
      owner = "lcpz";
      repo = "awesome-freedesktop";
      rev = "c82ad2960c5f0c84e765df68554c266ea7e9464d";
      fetchSubmodules = false;
      sha256 = "sha256-lQstCcTPUYUt5hzAJIyQ16crPngeOnUla7I4QiG6gEs=";
    });
    date = "2022-06-23";
  };
  lain = {
    pname = "lain";
    version = "438dd7481026519f1e924a2b3087e7cda559df57";
    src = fetchFromGitHub ({
      owner = "lcpz";
      repo = "lain";
      rev = "438dd7481026519f1e924a2b3087e7cda559df57";
      fetchSubmodules = false;
      sha256 = "sha256-sSgDhbvuy1AN0b5yd0qmjrun3y/HQbrhQ3jyYgeU7rI=";
    });
    date = "2022-10-20";
  };
  revelation = {
    pname = "revelation";
    version = "d8b58e3776ec0ace45b5bc1160e322b69fa16d6f";
    src = fetchFromGitHub ({
      owner = "guotsuan";
      repo = "awesome-revelation";
      rev = "d8b58e3776ec0ace45b5bc1160e322b69fa16d6f";
      fetchSubmodules = false;
      sha256 = "sha256-YwIQxjKJFgJdCwPs1Vq7JrmmdN3PVxLKofVOiWQZu7Y=";
    });
    date = "2020-08-07";
  };
  sharedtags = {
    pname = "sharedtags";
    version = "2a4396ea777de75258777948a93389714206bd93";
    src = fetchFromGitHub ({
      owner = "Drauthius";
      repo = "awesome-sharedtags";
      rev = "2a4396ea777de75258777948a93389714206bd93";
      fetchSubmodules = false;
      sha256 = "sha256-YTDKuUqUanh4AWOyEQUKjf3LwkicEuS1gJIVOg6U8iE=";
    });
    date = "2022-01-02";
  };
}
