# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  iosevka = {
    pname = "iosevka";
    version = "v1.3.2";
    src = fetchurl {
      url = "https://github.com/viperML/iosevka/releases/download/v1.3.2/iosevka-ttf-zip.zip";
      sha256 = "sha256-v1FPQ3HYbsRUxdP0Y8YDovEoghbIa1eu9je8bO7d0XM=";
    };
  };
}
