# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  iosevka = {
    pname = "iosevka";
    version = "v1.5.2";
    src = fetchurl {
      url = "https://github.com/viperML/iosevka/releases/download/v1.5.2/iosevka.zip";
      sha256 = "sha256-jD1BYmILVy1MYAVhuqE/MkxfZ26pIsmPx/C6bnKhTNY=";
    };
  };
}
