# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  iosevka = {
    pname = "iosevka";
    version = "v1.4.1";
    src = fetchurl {
      url = "https://github.com/viperML/iosevka/releases/download/v1.4.1/iosevka.zip";
      sha256 = "sha256-yD1wFA6F4k1kszd5p7L4mS5Ma88lUqImWhPwi7wVSww=";
    };
  };
}
