# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  picom = {
    pname = "picom";
    version = "7198874fc9823dbad666c755bf8a648283f892b5";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "7198874fc9823dbad666c755bf8a648283f892b5";
      fetchSubmodules = false;
      sha256 = "sha256-SxC01Yl0OxMv2/ibhR9YINYtmysxdQadawRIYflP9X4=";
    });
    date = "2022-11-30";
  };
}
