# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  picom = {
    pname = "picom";
    version = "cee12875625465292bc11bf09dc8ab117cae75f4";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "cee12875625465292bc11bf09dc8ab117cae75f4";
      fetchSubmodules = false;
      sha256 = "sha256-lVwBwOvzn4ro1jInRuNvn1vQuwUHUp4MYrDaFRmW9pc=";
    });
    date = "2023-01-29";
  };
}
