# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  picom = {
    pname = "picom";
    version = "6bcda50170031ef95fa02bc1bf94f87947c66e44";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "6bcda50170031ef95fa02bc1bf94f87947c66e44";
      fetchSubmodules = false;
      sha256 = "sha256-T/Osl7dNl4OF5C0W1pLtPJ8qsH4YtC5QNAehrLUqFC4=";
    });
    date = "2022-11-22";
  };
}
