# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hlargs = {
    pname = "hlargs";
    version = "30fe1b3de2b7614f061be4fc9c71984a2b87e50a";
    src = fetchFromGitHub {
      owner = "m-demare";
      repo = "hlargs.nvim";
      rev = "30fe1b3de2b7614f061be4fc9c71984a2b87e50a";
      fetchSubmodules = false;
      sha256 = "sha256-V3XG1SCBz+EvObW7JSNIUxGZLv6zoRXyap7nRETmUA8=";
    };
    date = "2024-05-18";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "6ac181b5733518040a33017dde654059cd771b7c";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "6ac181b5733518040a33017dde654059cd771b7c";
      fetchSubmodules = false;
      sha256 = "sha256-GRF/6AobXHamw8TZ3FjL7SI6ulcpwpcohsIuZeCSh2A=";
    };
    date = "2024-05-23";
  };
  nvim-transparent = {
    pname = "nvim-transparent";
    version = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
    src = fetchFromGitHub {
      owner = "xiyaowong";
      repo = "nvim-transparent";
      rev = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
      fetchSubmodules = false;
      sha256 = "sha256-wT+7rmp08r0XYGp+MhjJX8dsFTar8+nf10CV9OdkOSk=";
    };
    date = "2023-11-13";
  };
  org-bullets-nvim = {
    pname = "org-bullets-nvim";
    version = "3623e86e0fa6d07f45042f7207fc333c014bf167";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "org-bullets.nvim";
      rev = "3623e86e0fa6d07f45042f7207fc333c014bf167";
      fetchSubmodules = false;
      sha256 = "sha256-aIEe1dgUmDzu9kl33JCNcgyfp8DymURltH0HcZfph0Y=";
    };
    date = "2024-02-21";
  };
}
