# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hlargs = {
    pname = "hlargs";
    version = "cc0d9ee75e5ffba730393049119361b9e3a5b1b6";
    src = fetchFromGitHub {
      owner = "m-demare";
      repo = "hlargs.nvim";
      rev = "cc0d9ee75e5ffba730393049119361b9e3a5b1b6";
      fetchSubmodules = false;
      sha256 = "sha256-UAB1vXypJye0UeOo64mHhTuTKcCbwB1AQDFarbLEUAo=";
    };
    date = "2024-06-28";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "6ac181b5733518040a33017dde654059cd771b7c";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "6ac181b5733518040a33017dde654059cd771b7c";
      fetchSubmodules = false;
      sha256 = "sha256-GRF/6AobXHamw8TZ3FjL7SI6ulcpwpcohsIuZeCSh2A=";
    };
    date = "2024-05-23";
  };
  nvim-paredit = {
    pname = "nvim-paredit";
    version = "3e5838290dd57116457e4b11eb6ba21e83b260a4";
    src = fetchFromGitHub {
      owner = "ekaitz-zarraga";
      repo = "nvim-paredit-scheme";
      rev = "3e5838290dd57116457e4b11eb6ba21e83b260a4";
      fetchSubmodules = false;
      sha256 = "sha256-gzZJlN8LO1SH0joqgQgGIlkCVreccF8yxRYoinB9tU0=";
    };
    date = "2024-01-27";
  };
  nvim-transparent = {
    pname = "nvim-transparent";
    version = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
    src = fetchFromGitHub {
      owner = "xiyaowong";
      repo = "nvim-transparent";
      rev = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
      fetchSubmodules = false;
      sha256 = "sha256-wT+7rmp08r0XYGp+MhjJX8dsFTar8+nf10CV9OdkOSk=";
    };
    date = "2023-11-13";
  };
  org-bullets-nvim = {
    pname = "org-bullets-nvim";
    version = "7e76e04827ac3fb13fc645a6309ac14203c4ca6a";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "org-bullets.nvim";
      rev = "7e76e04827ac3fb13fc645a6309ac14203c4ca6a";
      fetchSubmodules = false;
      sha256 = "sha256-bxiL88uUa0Zd/HL7RcC/XVhbkgdlFr6MmlQfkpxFybE=";
    };
    date = "2024-07-09";
  };
}
