# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nushell = {
    pname = "nushell";
    version = "7e949595bdd31f197894580daf8ea84cd2ce51ca";
    src = fetchFromGitHub ({
      owner = "nushell";
      repo = "nushell";
      rev = "7e949595bdd31f197894580daf8ea84cd2ce51ca";
      fetchSubmodules = false;
      sha256 = "sha256-ScxKP4q6UMEwDlVITbhSGIl2L3zmEhT1zGx8WIsPLZA=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./nushell-7e949595bdd31f197894580daf8ea84cd2ce51ca/Cargo.lock;
      outputHashes = {
        "nu-ansi-term-0.46.0" = "sha256-gx6DxsQYpxMee0bXKqD7VbRPQw1nunxoNxxzvfmm5gM=";
        "reedline-0.16.0" = "sha256-MmRxWUD0ZrED24uMp/h5JFmvKZciR/a2uF+xWngLyRM=";
      };
    };
    date = "2023-03-08";
  };
}
