# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nushell = {
    pname = "nushell";
    version = "b1e7bb899a5554b397b33971a8680684ca1a9ad8";
    src = fetchFromGitHub ({
      owner = "nushell";
      repo = "nushell";
      rev = "b1e7bb899a5554b397b33971a8680684ca1a9ad8";
      fetchSubmodules = false;
      sha256 = "sha256-fwdAsEpuT5NhqDFpW87fwsbcj44h/p+QAnSno30cpqs=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./nushell-b1e7bb899a5554b397b33971a8680684ca1a9ad8/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2023-02-24";
  };
}
