# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nushell = {
    pname = "nushell";
    version = "f7b8f97873228396954c31574a1a12ac3f7b6c65";
    src = fetchFromGitHub ({
      owner = "nushell";
      repo = "nushell";
      rev = "f7b8f97873228396954c31574a1a12ac3f7b6c65";
      fetchSubmodules = false;
      sha256 = "sha256-mYOsL7fSDH4b2YO3EMi1Ke1y+pg1XDFZjevaBM5+vCo=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./nushell-f7b8f97873228396954c31574a1a12ac3f7b6c65/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2023-03-06";
  };
}
