# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  hcl = {
    pname = "hcl";
    version = "v2.14.0";
    src = fetchFromGitHub ({
      owner = "hashicorp";
      repo = "hcl";
      rev = "v2.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-Rx073Ob7CqaPEGIskJHW/xmt4S+WE/AWKewXpjY3kQ4=";
    });
  };
}
