# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hcl = {
    pname = "hcl";
    version = "v2.14.1";
    src = fetchFromGitHub ({
      owner = "hashicorp";
      repo = "hcl";
      rev = "v2.14.1";
      fetchSubmodules = false;
      sha256 = "sha256-XH/qSl16LQThj9ghwlSGJuSsez7VxsZS9Sun7F2sT7Y=";
    });
  };
}
