# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hcl = {
    pname = "hcl";
    version = "v2.16.0";
    src = fetchFromGitHub ({
      owner = "hashicorp";
      repo = "hcl";
      rev = "v2.16.0";
      fetchSubmodules = false;
      sha256 = "sha256-dsso9KQMZhFgnN6CxoQbXRnjbfaKeLRA8ZEYc9NYEe0=";
    });
  };
}
