[hyprland]
# src.github = "hyprwm/Hyprland"
src.git = "https://github.com/hyprwm/Hyprland"
fetch.git = "https://github.com/hyprwm/Hyprland"

[nvfetcher]
src.github = "berberman/nvfetcher"
fetch.git = "https://github.com/berberman/nvfetcher.git"

[nix]
src.github_tag = "NixOS/nix"
fetch.git = "https://github.com/nixos/nix.git"

# [helix]
# src.github = "helix-editor/helix"
# fetch.git = "https://github.com/helix-editor/helix.git"
[lanzaboote]
src.github_tag = "nix-community/lanzaboote"
fetch.git = "https://github.com/nix-community/lanzaboote"
