# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  helix = {
    pname = "helix";
    version = "23.03";
    src = fetchgit {
      url = "https://github.com/helix-editor/helix.git";
      rev = "23.03";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Qrn3mB6bb1DSvKxOJ9oAlxuMk64Fzg2W4BVmk6y3deA=";
    };
  };
  hyprland = {
    pname = "hyprland";
    version = "v0.24.1";
    src = fetchgit {
      url = "https://github.com/hyprwm/Hyprland.git";
      rev = "v0.24.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Ts2rAsRJUxAUnEr8/xFzgBovn8LqaF3/sLIR8t0SM/0=";
    };
  };
  nix = {
    pname = "nix";
    version = "2.14.1";
    src = fetchgit {
      url = "https://github.com/nixos/nix.git";
      rev = "2.14.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-5aCmGZbsFcLIckCDfvnPD4clGPQI7qYAqHYlttN/Wkg=";
    };
  };
  nvfetcher = {
    pname = "nvfetcher";
    version = "0.6.0";
    src = fetchgit {
      url = "https://github.com/berberman/nvfetcher.git";
      rev = "0.6.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-LrY0K1yya3nvRlGDc98wm68ozVj7E6a1EXXEr7eHp8E=";
    };
  };
}
