# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nix = {
    pname = "nix";
    version = "2.15.0";
    src = fetchgit {
      url = "https://github.com/nixos/nix.git";
      rev = "2.15.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-hNHfvmb1bIWwqFT5nesQgwh4V0OlyZHxj5ZVSQbZ+p4=";
    };
  };
}
