# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hyprland = {
    pname = "hyprland";
    version = "v0.22.0beta";
    src = fetchgit {
      url = "https://github.com/hyprwm/Hyprland.git";
      rev = "v0.22.0beta";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qhz5LfRLxTe5pOgo8+1g8OalloBt4jrd9p3zUs81yvI=";
    };
  };
  nix = {
    pname = "nix";
    version = "2.14.1";
    src = fetchgit {
      url = "https://github.com/nixos/nix.git";
      rev = "2.14.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-5aCmGZbsFcLIckCDfvnPD4clGPQI7qYAqHYlttN/Wkg=";
    };
  };
  nvfetcher = {
    pname = "nvfetcher";
    version = "0.6.0";
    src = fetchgit {
      url = "https://github.com/berberman/nvfetcher.git";
      rev = "0.6.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-LrY0K1yya3nvRlGDc98wm68ozVj7E6a1EXXEr7eHp8E=";
    };
  };
}
