# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  colloid = {
    pname = "colloid";
    version = "2022-07-18";
    src = fetchFromGitHub ({
      owner = "vinceliuice";
      repo = "Colloid-gtk-theme";
      rev = "2022-07-18";
      fetchSubmodules = false;
      sha256 = "sha256-dWYRTwfQRMBdg+htxpWatF325rToaovF/43LxX6I1GI=";
    });
  };
}
