-- Generated by nwg-displays on 2026-06-08 at 08:38:04. Do not edit manually.

hl.monitor({
    output = "desc:AU Optronics 0xC3A3",
    mode = "1920x1200@60.03",
    position = "2613x1173",
    scale = 1.25
})
hl.monitor({
    output = "desc:Microstep MSI MAG271CQR 0x00000386",
    mode = "2560x1440@143.97",
    position = "4149x0",
    scale = 1.0
})
