# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  Minion3665-nix-original = {
    pname = "Minion3665-nix-original";
    version = "a9fab18a9176e72402a4ad4ce73ccc6c2804bd53";
    src = fetchFromGitHub ({
      owner = "Minion3665";
      repo = "nix";
      rev = "a9fab18a9176e72402a4ad4ce73ccc6c2804bd53";
      fetchSubmodules = false;
      sha256 = "sha256-fY6bs8tSAxJ75jfE/bGyw7P5zNemVDqmpDE57LHkLGM=";
    });
  };
  Minion3665-nix-patched = {
    pname = "Minion3665-nix-patched";
    version = "c7302640120ff9fff6c3a653c22fa678efbeb903";
    src = fetchFromGitHub ({
      owner = "Minion3665";
      repo = "nix";
      rev = "c7302640120ff9fff6c3a653c22fa678efbeb903";
      fetchSubmodules = false;
      sha256 = "sha256-Nh7+fyVqPyvrxHQaCBNY1ytBAKcS0jnImkH/XpoxDRE=";
    });
  };
  dramforever = {
    pname = "dramforever";
    version = "ae7f0b7c5d39eec5941fe21e9f202106bdea9ac2";
    src = fetchFromGitHub ({
      owner = "dramforever";
      repo = "nix-dram";
      rev = "ae7f0b7c5d39eec5941fe21e9f202106bdea9ac2";
      fetchSubmodules = false;
      sha256 = "sha256-oPO+keK4S9daL9ubU51hZ+QOWVSMbZ56F20iFI9Px3s=";
    });
  };
}
