# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  project_x = {
    pname = "project_x";
    version = "31917eb0e8744d73e2cf3c57aa24a83a0692f830";
    src = fetchFromGitHub {
      owner = "vmargb";
      repo = "project-x";
      rev = "31917eb0e8744d73e2cf3c57aa24a83a0692f830";
      fetchSubmodules = false;
      sha256 = "sha256-oU0NSTZ+FwFR4tAcxXK4r4T+B1EeIGX1owIdwPiTlIc=";
    };
    date = "2026-06-12";
  };
}
