# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  minimal-emacs-d = {
    pname = "minimal-emacs-d";
    version = "a5569d57918676a0787bdecb5e7ab5bf4b9f4c75";
    src = fetchFromGitHub {
      owner = "jamescherti";
      repo = "minimal-emacs.d";
      rev = "a5569d57918676a0787bdecb5e7ab5bf4b9f4c75";
      fetchSubmodules = false;
      sha256 = "sha256-q9i55pwwOjvL7ki9EcGswwZATVJbonme0kMv57zta54=";
    };
    date = "2026-06-16";
  };
}
