# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  tym = {
    pname = "tym";
    version = "3.3.0";
    src = fetchFromGitHub ({
      owner = "endaaman";
      repo = "tym";
      rev = "3.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-ufIYJgbHmSJJbnx4hyDx0DmIjaGCxKXtiekcXcyka14=";
    });
  };
}
