# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xdg-ninja = {
    pname = "xdg-ninja";
    version = "ce2b79884f083d4ecb68b12da0148de2e63f3f09";
    src = fetchFromGitHub {
      owner = "b3nj5m1n";
      repo = "xdg-ninja";
      rev = "ce2b79884f083d4ecb68b12da0148de2e63f3f09";
      fetchSubmodules = false;
      sha256 = "sha256-QdzNQ3K1asHUQYdcLGr+WgWBCjBxrCT5TpZDN91YMFU=";
    };
    date = "2024-07-01";
  };
}
