# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xdg-ninja = {
    pname = "xdg-ninja";
    version = "45732bfcb6f62c92861f6549faa5006fd1e06266";
    src = fetchFromGitHub {
      owner = "b3nj5m1n";
      repo = "xdg-ninja";
      rev = "45732bfcb6f62c92861f6549faa5006fd1e06266";
      fetchSubmodules = false;
      sha256 = "sha256-+xClvXsQytuvhV2qwA69ejxTlDa/JBhZIx4T49ybrnA=";
    };
    date = "2024-05-13";
  };
}
