# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xdg-ninja = {
    pname = "xdg-ninja";
    version = "d56175dfbbb25541228c2d62e6b466a2ee60639b";
    src = fetchFromGitHub {
      owner = "b3nj5m1n";
      repo = "xdg-ninja";
      rev = "d56175dfbbb25541228c2d62e6b466a2ee60639b";
      fetchSubmodules = false;
      sha256 = "sha256-BtVqbKTyM/52e1nkZNLcXaP4kDiFP/uDTLVugDDYJv8=";
    };
    date = "2024-06-05";
  };
}
