# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clipmon = {
    pname = "clipmon";
    version = "697ea408c793211f0f698fe9fbdd8a84bb4a6f44";
    src = fetchgit {
      url = "https://git.sr.ht/~whynothugo/clipmon";
      rev = "697ea408c793211f0f698fe9fbdd8a84bb4a6f44";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pEM9I/SvAcHVpz5qCuyr7Gtn8nnoTO1aEzvUL2xR5Vk=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./clipmon-697ea408c793211f0f698fe9fbdd8a84bb4a6f44/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2024-03-09";
  };
}
