# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clipmon = {
    pname = "clipmon";
    version = "2e338fdc2841c3b2de9271d90fcceceda9e45d29";
    src = fetchgit {
      url = "https://git.sr.ht/~whynothugo/clipmon";
      rev = "2e338fdc2841c3b2de9271d90fcceceda9e45d29";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-bEMgJYz3e2xwMO084bmCT1oZImcmO3xH6rIsjvAxnTA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./clipmon-2e338fdc2841c3b2de9271d90fcceceda9e45d29/Cargo.lock;
      outputHashes = { };
    };
    date = "2022-08-28";
  };
}
