# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  fzf = {
    pname = "fzf";
    version = "v9.6";
    src = fetchFromGitHub ({
      owner = "PatrickF1";
      repo = "fzf.fish";
      rev = "v9.6";
      fetchSubmodules = false;
      sha256 = "sha256-89uquxtYN2NXNgV6u72LzuE83IwjMvGquvTpGue8OWQ=";
    });
  };
}
