# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  fzf = {
    pname = "fzf";
    version = "v9.4";
    src = fetchFromGitHub ({
      owner = "PatrickF1";
      repo = "fzf.fish";
      rev = "v9.4";
      fetchSubmodules = false;
      sha256 = "sha256-Lvr/6rkCDJCXRuUh2mD5YUClQ0NMUdoWmaBFCSMf2oU=";
    });
  };
}
