{
  pkgs,
  self',
  config,
  lib,
  ...
}: {
  nixpkgs.config.allowUnfree = true;

  unsafeFlakePath = "/home/ayats/Documents/dotfiles";

  home.packages = [
    pkgs.vscode
    self'.packages.wezterm
    pkgs.onlyoffice-bin
    pkgs.sops
    pkgs.age
    pkgs.d-spy
    pkgs.rsync
    pkgs.ltex-ls
    self'.packages.ungoogled-chromium

    # global dev
    pkgs.just
    pkgs.clang-tools
    pkgs.hyperfine
    pkgs.cntr
    pkgs.sshfs
    pkgs.strace
    pkgs.gdb
    pkgs.tokio-console
  ];

  sops = {
    age.keyFile = "${config.xdg.configHome}/sops/age/keys.txt";
    defaultSopsFile = ./private.yaml;
    secrets.git_config = {
      path = "${config.xdg.configHome}/git/local";
    };
    secrets.ssh_config = {
      sopsFile = ../../misc/private/ssh.yaml;
      path = "${config.home.homeDirectory}/.ssh/config-generic";
    };
  };

  home.activation.ssh_config = config.lib.dag.entryAfter ["writeBoundary"] ''
    mkdir -pv ~/.ssh
    touch ~/.ssh/config-device
    rm -rf ~/.ssh/config
    echo "## WARNING: THIS FILE WAS AUTOGENERATED" > ~/.ssh/config
    cat ~/.ssh/config-device >> ~/.ssh/config
    cat ~/.ssh/config-generic >> ~/.ssh/config
  '';
}
