# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  fzf = {
    pname = "fzf";
    version = "v9.1";
    src = fetchFromGitHub ({
      owner = "PatrickF1";
      repo = "fzf.fish";
      rev = "v9.1";
      fetchSubmodules = false;
      sha256 = "sha256-OLmPtgUVX+/uiZg6lMl1xF4MHGVZUpTVota68coexWw=";
    });
  };
  sponge = {
    pname = "sponge";
    version = "1.0.4";
    src = fetchFromGitHub ({
      owner = "andreiborisov";
      repo = "sponge";
      rev = "1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-+GGfFC/hH7A8n9Wwojt5PW96fSzvRhThnZ3pLeWEqds=";
    });
  };
}
