# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  fzf = {
    pname = "fzf";
    version = "v9.2";
    src = fetchFromGitHub ({
      owner = "PatrickF1";
      repo = "fzf.fish";
      rev = "v9.2";
      fetchSubmodules = false;
      sha256 = "sha256-XmRGe39O3xXmTvfawwT2mCwLIyXOlQm7f40mH5tzz+s=";
    });
  };
}
