# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  swayfx = {
    pname = "swayfx";
    version = "50e2422e743c0b337097dd2367f82e0d4b20fabc";
    src = fetchFromGitHub ({
      owner = "WillPower3309";
      repo = "swayfx";
      rev = "50e2422e743c0b337097dd2367f82e0d4b20fabc";
      fetchSubmodules = false;
      sha256 = "sha256-j0roxTgZTTddvjwn7QWf/k3KnQFp5HyzeG2gbwEBScs=";
    });
    date = "2023-04-21";
  };
}
