# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  swayfx = {
    pname = "swayfx";
    version = "ac31a612164828ca6ae5478332eee3cd2317ffdc";
    src = fetchFromGitHub ({
      owner = "WillPower3309";
      repo = "swayfx";
      rev = "ac31a612164828ca6ae5478332eee3cd2317ffdc";
      fetchSubmodules = false;
      sha256 = "sha256-ROy8sD8/W1Sv1vF5D0EBSBm6W0KiWsuJGnQMRk6zT3Y=";
    });
    date = "2023-03-12";
  };
}
