# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  swayfx = {
    pname = "swayfx";
    version = "7d5d7a3022eb17835cea7af7290b1a5d2fe4b03a";
    src = fetchFromGitHub ({
      owner = "WillPower3309";
      repo = "swayfx";
      rev = "7d5d7a3022eb17835cea7af7290b1a5d2fe4b03a";
      fetchSubmodules = false;
      sha256 = "sha256-tMoiwFO/AVTV7GoGMSu3XQimFnK8vv3yzf+D41kTJoE=";
    });
    date = "2023-03-20";
  };
}
