# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nix-software-center = {
    pname = "nix-software-center";
    version = "0.1.1";
    src = fetchFromGitHub ({
      owner = "vlinkz";
      repo = "nix-software-center";
      rev = "0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-NpA2w1EOi+zE3JiB/oRC9RtSWlAqWr0cvNP5r5d6MTs=";
    });
  };
}
