# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  nix-software-center = {
    pname = "nix-software-center";
    version = "0.1.0";
    src = fetchFromGitHub ({
      owner = "vlinkz";
      repo = "nix-software-center";
      rev = "0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-d4LAIaiCU91LAXfgPCWOUr2JBkHj6n0JQ25EqRIBtBM=";
    });
  };
}
