# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  git-jlog = {
    pname = "git-jlog";
    version = "0ab76e6749de1f8c3859ee20e277c7fe2b1c44d7";
    src = fetchgit {
      url = "https://gitlab.com/viperML/git-jlog";
      rev = "0ab76e6749de1f8c3859ee20e277c7fe2b1c44d7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AtGTkd0++uPPESS/YyQ3yP8sbWs6YpWo7TNkpYxDOqs=";
    };
    date = "2026-03-08";
  };
}
