# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  git-jlog = {
    pname = "git-jlog";
    version = "fffc2dbe8e51ee21fa323345a278d82725c59f78";
    src = fetchgit {
      url = "https://gitlab.com/viperML/git-jlog";
      rev = "fffc2dbe8e51ee21fa323345a278d82725c59f78";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kiv55dTmIH+kEK5Eo1qktk0dWkpafYGAsR8NWR9i3Yw=";
    };
    date = "2026-03-08";
  };
}
