# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  xdg-ninja = {
    pname = "xdg-ninja";
    version = "2a4c7beed9991ed3c112a75799a4d2cb1d1efd50";
    src = fetchFromGitHub ({
      owner = "b3nj5m1n";
      repo = "xdg-ninja";
      rev = "2a4c7beed9991ed3c112a75799a4d2cb1d1efd50";
      fetchSubmodules = false;
      sha256 = "sha256-Q6mK+qwrC3jWuQYkr7s3nCNRiux091ISdHB6ifJ+WZY=";
    });
    date = "2022-09-25";
  };
}
