# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xdg-ninja = {
    pname = "xdg-ninja";
    version = "b0a4eebfbd4f8edc446f80f44605b576dfd9dc71";
    src = fetchFromGitHub {
      owner = "b3nj5m1n";
      repo = "xdg-ninja";
      rev = "b0a4eebfbd4f8edc446f80f44605b576dfd9dc71";
      fetchSubmodules = false;
      sha256 = "sha256-ft8WxBuYpUBF+Ae0s2DT5bfic4SHhDr2LwlKCxFBKUQ=";
    };
    date = "2023-11-08";
  };
}
