# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xdg-ninja = {
    pname = "xdg-ninja";
    version = "dacfaaca99b44d87798f750626ad27fabad92f63";
    src = fetchFromGitHub {
      owner = "b3nj5m1n";
      repo = "xdg-ninja";
      rev = "dacfaaca99b44d87798f750626ad27fabad92f63";
      fetchSubmodules = false;
      sha256 = "sha256-stsj6wU54/XZTcEpjMWCm9ius6isHBVURyNI3o2EYrk=";
    };
    date = "2024-02-08";
  };
}
