abbr -S gd="git diff"
abbr -S gdd="git diff | grep -v '^diff\|^index' | bat"
abbr -S ga="git add"
abbr -S gaa="git add --all ."
abbr -S gbd="git branch -D"
abbr -S gs="git status"
abbr -S gca="git commit -a -m"
abbr -S gm="git merge"
abbr -S gpt="git push --tags"
abbr -S gp="git push"
abbr -S grh="git reset --hard"
abbr -S gb="git branch"
abbr -S gcob="git checkout -b"
abbr -S gco="git checkout"
abbr -S gba="git branch -a"
abbr -S gcp="git cherry-pick"
abbr -S gl="git log --pretty=format:\"%Cgreen%h%Creset - %Cblue%an%Creset @ %ar : %s\""
abbr -S gl2="git log --pretty='format:%Cgreen%h%Creset %an - %s' --graph"
abbr -S glv="git log --stat"
abbr -S gpom="git pull origin master"
abbr -S gcd='cd "`git rev-parse --show-toplevel`"'
abbr -S gcf="git clean -fd"
abbr -S gcod="git checkout -- ."
abbr -S gpum="git pull upstream master"
abbr -S gpod="git push origin --delete"
abbr -S gsu="git status -uno"
abbr -S gcm="git commit -m"
abbr -S gcv="git commit --verbose"
abbr -S gc="git commit --verbose"
abbr -S gds="git diff | sublime"
abbr -S grm="git reset HEAD"
abbr -S gacm="git add . --all; git commit --verbose"
abbr -S gtd="git log --tags --simplify-by-decoration --pretty=\"format:%ai %d\""
abbr -S grs="git shortlog -s -n --all --no-merges"
abbr -S gss="git status --short"
abbr -S gr="cd (git-root)"
