# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  zsh-abbr = {
    pname = "zsh-abbr";
    version = "v4.7.1";
    src = fetchFromGitHub ({
      owner = "olets";
      repo = "zsh-abbr";
      rev = "v4.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-6T27TTD4V3nzx1D8vhMpn2FIodYtLkOBoi6J7GYNV6k=";
    });
  };
  zsh-autosuggestions = {
    pname = "zsh-autosuggestions";
    version = "a411ef3e0992d4839f0732ebeb9823024afaaaa8";
    src = fetchFromGitHub ({
      owner = "zsh-users";
      repo = "zsh-autosuggestions";
      rev = "a411ef3e0992d4839f0732ebeb9823024afaaaa8";
      fetchSubmodules = false;
      sha256 = "sha256-KLUYpUu4DHRumQZ3w59m9aTW6TBKMCXl2UcKi4uMd7w=";
    });
  };
  zsh-completions = {
    pname = "zsh-completions";
    version = "0.34.0";
    src = fetchFromGitHub ({
      owner = "zsh-users";
      repo = "zsh-completions";
      rev = "0.34.0";
      fetchSubmodules = false;
      sha256 = "sha256-qSobM4PRXjfsvoXY6ENqJGI9NEAaFFzlij6MPeTfT0o=";
    });
  };
  zsh-syntax-highlighting = {
    pname = "zsh-syntax-highlighting";
    version = "caa749d030d22168445c4cb97befd406d2828db0";
    src = fetchFromGitHub ({
      owner = "zsh-users";
      repo = "zsh-syntax-highlighting";
      rev = "caa749d030d22168445c4cb97befd406d2828db0";
      fetchSubmodules = false;
      sha256 = "sha256-YV9lpJ0X2vN9uIdroDWEize+cp9HoKegS3sZiSpNk50=";
    });
  };
}
