# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hlargs = {
    pname = "hlargs";
    version = "e881f3a424139cc70c83121ec548732efdd67682";
    src = fetchFromGitHub {
      owner = "m-demare";
      repo = "hlargs.nvim";
      rev = "e881f3a424139cc70c83121ec548732efdd67682";
      fetchSubmodules = false;
      sha256 = "sha256-pp8FBDqNiFTVr0PVyJfZvB9Mdvzuse54ug56fT1Y2nQ=";
    };
    date = "2024-02-01";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "2349e8357864bf0ef45d40f491f8e1e6465485b0";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "2349e8357864bf0ef45d40f491f8e1e6465485b0";
      fetchSubmodules = false;
      sha256 = "sha256-duFl8bdsVtzG05v1BdzU9Z82OKd7qqRfmjNDhr2K0xs=";
    };
    date = "2024-02-06";
  };
  nvim-transparent = {
    pname = "nvim-transparent";
    version = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
    src = fetchFromGitHub {
      owner = "xiyaowong";
      repo = "nvim-transparent";
      rev = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
      fetchSubmodules = false;
      sha256 = "sha256-wT+7rmp08r0XYGp+MhjJX8dsFTar8+nf10CV9OdkOSk=";
    };
    date = "2023-11-13";
  };
}
