# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hlargs = {
    pname = "hlargs";
    version = "6218a401824c5733ac50b264991b62d064e85ab2";
    src = fetchFromGitHub {
      owner = "m-demare";
      repo = "hlargs.nvim";
      rev = "6218a401824c5733ac50b264991b62d064e85ab2";
      fetchSubmodules = false;
      sha256 = "sha256-bH0OOf5T4Z96Td4ZBV1q8DI/bO1pV8DwqEWho6jeggg=";
    };
    date = "2023-09-15";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "010bedf0b7c01ab4d4e4e896a8527d97c222351d";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "010bedf0b7c01ab4d4e4e896a8527d97c222351d";
      fetchSubmodules = false;
      sha256 = "sha256-e1jf7HyP9nu/HQHZ0QK+o7Aljk7Hu2iK+LNw3166wn8=";
    };
    date = "2023-11-06";
  };
  nvim-transparent = {
    pname = "nvim-transparent";
    version = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
    src = fetchFromGitHub {
      owner = "xiyaowong";
      repo = "nvim-transparent";
      rev = "fd35a46f4b7c1b244249266bdcb2da3814f01724";
      fetchSubmodules = false;
      sha256 = "sha256-wT+7rmp08r0XYGp+MhjJX8dsFTar8+nf10CV9OdkOSk=";
    };
    date = "2023-11-13";
  };
}
