# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  iosevka = {
    pname = "iosevka";
    version = "v1.5.4";
    src = fetchurl {
      url = "https://github.com/viperML/iosevka/releases/download/v1.5.4/iosevka-normal.zip";
      sha256 = "sha256-6ldVevkLak94C0M0kpNN+RohTU0LI+Prr1oP88tHMXg=";
    };
  };
}
