#!/bin/env python
execx($(starship init xonsh))

xontrib load abbrevs
abbrevs['n'] = 'nvim'

abbrevs['nuse'] = 'sudo nvim /etc/portage/package.use/my-use'

abbrevs['p'] = 'python'
abbrevs['n'] = 'nvim'
abbrevs['netboot'] = 'docker run --net=host pixiecore/pixiecore:master quick xyz --dhcp-no-bind'
abbrevs['ns'] = 'nix-shell --run xonsh --packages'
abbrevs['x'] = 'xdg-open'
abbrevs['s'] = 'sudo'
abbrevs['ss'] = 'sudo systemctl'
abbrevs['us'] = 'systemctl --user'
abbrevs['se'] = 'sudo -E systemctl edit'
abbrevs['sf'] = 'sudo --preserve-env=PATH (which fish)'
abbrevs['eq'] = 'equery'
abbrevs['nacc'] = 'sudo nvim /etc/portage/package.accept_keywords'
abbrevs['gd'] = "git diff -M"
abbrevs['ga'] = "git add"
abbrevs['gaa'] = "git add --all ."
abbrevs['gbd'] = "git branch -D"
abbrevs['gs'] = "git status"
abbrevs['gca'] = "git commit -m"
abbrevs['gm'] = "git merge"
abbrevs['gpt'] = "git push --tags"
abbrevs['gp'] = "git push"
abbrevs['grh'] = "git reset --hard"
abbrevs['gb'] = "git branch"
abbrevs['gcob'] = "git checkout -b"
abbrevs['gco'] = "git checkout"
abbrevs['gba'] = "git branch -a"
abbrevs['gcp'] = "git cherry-pick"
abbrevs['gl'] = "git log --pretty=format:\"%Cgreen%h%Creset - %Cblue%an%Creset @ %ar : %s\""
abbrevs['gl2'] = "git log --pretty='format:%Cgreen%h%Creset %an - %s' --graph"
abbrevs['glv'] = "git log --stat"
abbrevs['gpom'] = "git pull origin master"
abbrevs['gcd'] = 'cd "`git rev-parse --show-toplevel`"'
abbrevs['gcf'] = "git clean -fd"
abbrevs['gcod'] = "git checkout -- ."
abbrevs['gpum'] = "git pull upstream master"
abbrevs['gpod'] = "git push origin --delete"
abbrevs['gsu'] = "git status -uno"
abbrevs['gcm'] = "git commit -m"
abbrevs['gcv'] = "git commit --verbose"
abbrevs['gc'] = "git commit --verbose"
abbrevs['gds'] = "git diff | sublime"
abbrevs['grm'] = "git reset HEAD"
abbrevs['gacm'] = "git add . --all; git commit --verbose"
abbrevs['gtd'] = "git log --tags --simplify-by-decoration --pretty=\"format:%ai %d\""
abbrevs['grs'] = "git shortlog -s -n --all --no-merges"
abbrevs['gss'] = "git status --short"
