theme = "ayu_evolve"

[editor]
line-number = "relative"
cursorline = true
true-color = true
bufferline = "always"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spinner", "diagnostics"]
right = ["file-base-name", "file-type", "selections", "position", "file-encoding"]

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true

# https://github.com/LGUG2Z/helix-vim
[keys.normal]
Z = { Z = ":wq", Q = ":q!" }
esc = ["collapse_selection", "keep_primary_selection"]
