theme = "ayu_evolve"

[editor]
line-number = "relative"
cursorline = true
true-color = true
bufferline = "always"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

# https://github.com/LGUG2Z/helix-vim
[keys.normal]
Z = { Z = ":wq", Q = ":q!" }
esc = ["collapse_selection", "keep_primary_selection"]
