# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  tailscale-systray = {
    pname = "tailscale-systray";
    version = "8e943debe7801a79c0e146cf9f53f0b9aa9d5e72";
    src = fetchFromGitHub ({
      owner = "mattn";
      repo = "tailscale-systray";
      rev = "8e943debe7801a79c0e146cf9f53f0b9aa9d5e72";
      fetchSubmodules = false;
      sha256 = "sha256-iIKth2qPc8S5h0ebasoiIGiEEy+mip8Ris1HWW/p6Ko=";
    });
    date = "2022-06-26";
  };
}
