# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  iosevka = {
    pname = "iosevka";
    version = "v15.6.3";
    src = fetchFromGitHub ({
      owner = "be5invis";
      repo = "Iosevka";
      rev = "v15.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-wsFx5sD1CjQTcmwpLSt97OYFI8GtVH54uvKQLU1fWTg=";
    });
  };
}
