#!/usr/bin/env bash
hc() {
    herbstclient "$@"
}
hc emit_hook reload
hc keyunbind --all
hc detect_monitors

Mod=Mod4
hc set focus_follows_mouse true


# ████████╗ █████╗  ██████╗ ███████╗
# ╚══██╔══╝██╔══██╗██╔════╝ ██╔════╝
#    ██║   ███████║██║  ███╗███████╗
#    ██║   ██╔══██║██║   ██║╚════██║
#    ██║   ██║  ██║╚██████╔╝███████║
#    ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )     

# Names
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


# ██╗  ██╗███████╗██╗   ██╗██████╗ ██╗███╗   ██╗██████╗ ███████╗
# ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔══██╗██║████╗  ██║██╔══██╗██╔════╝
# █████╔╝ █████╗   ╚████╔╝ ██████╔╝██║██╔██╗ ██║██║  ██║███████╗
# ██╔═██╗ ██╔══╝    ╚██╔╝  ██╔══██╗██║██║╚██╗██║██║  ██║╚════██║
# ██║  ██╗███████╗   ██║   ██████╔╝██║██║ ╚████║██████╔╝███████║
# ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═════╝ ╚═╝╚═╝  ╚═══╝╚═════╝ ╚══════╝
hc keybind $Mod-Shift-r reload

# Apps
hc keybind $Mod-Return spawn kitty
hc keybind $Mod-space  spawn rofi -show drun
hc keybind $Mod-e      spawn dolphin

# Clients
hc keybind $Mod-q close
hc keybind $Mod-z set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-z floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# Move clients
hc keybind $Mod-Shift-Left or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-Down  or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-Up    or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-Right or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# Frames
hc keybind $Mod-r remove
# Split frames
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Control-space split explode
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-x                                                  \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1


# Tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible


# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set snap_gap 30
hc set mouse_recenter_gap 0


# ████████╗██╗  ██╗███████╗███╗   ███╗███████╗
# ╚══██╔══╝██║  ██║██╔════╝████╗ ████║██╔════╝
#    ██║   ███████║█████╗  ██╔████╔██║█████╗  
#    ██║   ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══╝  
#    ██║   ██║  ██║███████╗██║ ╚═╝ ██║███████╗
#    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝
hc lock
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc pad 1 30 0 0 0
hc pad 0  0 0 0 0

# inner_color/inner_width
#       ╻        outer_color/outer_width
#       │                  ╻
#       │                  │
# ┌────╴│╶─────────────────┷─────┐ ⎫ border_width
# │     │      color             │ ⎬ + title_height
# │  ┌──┷─────────────────────┐  │ ⎭ + padding_top
# │  │====================....│  │
# │  │== window content ==....│  │
# │  │====================..╾──────── background_color
# │  │........................│  │
# │  └────────────────────────┘  │ ⎱ border_width +
# └──────────────────────────────┘ ⎰ padding_bottom

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color red
hc attr theme.background_color '#000000'

hc set window_gap 5

# Outer border
hc attr theme.border_width 5
hc attr theme.active.outer_color '#3E4A00'

# Inner border
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.active.inner_color '#3E4A00'


# Floating
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black

# Frame
hc set frame_padding 7
hc set frame_normal_opacity 70
hc set frame_active_opacity 70
hc set frame_transparent_width 40
hc set frame_gap 5

hc set smart_window_surroundings off
hc set smart_frame_surroundings onO
hc set always_show_frame on
hc set frame_bg_transparent on


# Frame Border
hc set frame_border_width 0
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'


# Title
hc attr theme.title_height 17
hc attr theme.title_font 'Sarasa Gothic J:pixelsize=12'
hc attr theme.padding_top 4  # space below the title's baseline (i.e. text depth)




# ██████╗ ██╗   ██╗██╗     ███████╗███████╗
# ██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
# ██████╔╝██║   ██║██║     █████╗  ███████╗
# ██╔══██╗██║   ██║██║     ██╔══╝  ╚════██║
# ██║  ██║╚██████╔╝███████╗███████╗███████║
# ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝
                                         
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'


hc unlock