#!/usr/bin/env bash
hc() {
    herbstclient "$@"
}
hc emit_hook reload
hc keyunbind --all


Mod=Mod4
hc set focus_follows_mouse true


# ████████╗ █████╗  ██████╗ ███████╗
# ╚══██╔══╝██╔══██╗██╔════╝ ██╔════╝
#    ██║   ███████║██║  ███╗███████╗
#    ██║   ██╔══██║██║   ██║╚════██║
#    ██║   ██║  ██║╚██████╔╝███████║
#    ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝
tag_names=( "" "﬏" "3" "4" "5" "6" "7" "" "" "")
tag_keys=( {1..9} 0 )

# Names
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


# ██╗  ██╗███████╗██╗   ██╗██████╗ ██╗███╗   ██╗██████╗ ███████╗
# ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔══██╗██║████╗  ██║██╔══██╗██╔════╝
# █████╔╝ █████╗   ╚████╔╝ ██████╔╝██║██╔██╗ ██║██║  ██║███████╗
# ██╔═██╗ ██╔══╝    ╚██╔╝  ██╔══██╗██║██║╚██╗██║██║  ██║╚════██║
# ██║  ██╗███████╗   ██║   ██████╔╝██║██║ ╚████║██████╔╝███████║
# ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═════╝ ╚═╝╚═╝  ╚═══╝╚═════╝ ╚══════╝
# Apps
hc keybind $Mod-Return spawn kitty
hc keybind $Mod-space spawn rofi -show combi
hc keybind $Mod-e spawn dolphin
hc keybind Print spawn flameshot gui
hc keybind Control+Print spawn  peek

# Other
hc keybind $Mod-Shift-r         reload
hc keybind $Mod-Control-r       spawn polybar-msg cmd restart
hc keybind F7 spawn pactl set-sink-volume @DEFAULT_SINK@ -2%
hc keybind F8 spawn pactl set-sink-volume @DEFAULT_SINK@ +2%

# hlwm-utils
hc keybind $Mod-m sh ~/.config/herbstluftwm/hlwm-utils/hlwm-menu/hlwm-menu.sh
# layout bindings (control or Control)
hc keybind $Mod-Control-v  spawn sh ~/.config/herbstluftwm/hlwm-utils/layouts/centered-master
hc keybind $Mod-Control-b  spawn sh ~/.config/herbstluftwm/hlwm-utils/layouts/dwindle
hc keybind $Mod-Control-n  spawn sh ~/.config/herbstluftwm/hlwm-utils/layouts/master-stack
hc keybind $Mod-Control-m  spawn sh ~/.config/herbstluftwm/hlwm-utils/layouts/vertical

# Reset to default
hc keybind $Mod-Control-c  sh ~/.config/herbstluftwm/hlwm-utils/layouts/reset


# Clients
hc keybind $Mod-q close
hc keybind $Mod-z set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-z floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-Shift-m spawn withlock LOCK-window termite --name "window" -e "~/.config/herbstluftwm/scripts/hidden_list.sh" #Unminimize all windows on current tag
# Move clients
hc keybind $Mod-Shift-Left or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-Down  or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-Up    or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-Right or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# Frames
hc keybind $Mod-r remove
# Split frames
hc keybind $Mod-u       split   bottom  0.7
hc keybind $Mod-o       split   right   0.7
hc keybind $Mod-i split explode
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-x                                                  \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1


# Tags
#hc keybind $Mod-period use_index +1 --skip-visible
#hc keybind $Mod-comma  use_index -1 --skip-visible


# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set snap_gap 30
hc set mouse_recenter_gap 0


# ████████╗██╗  ██╗███████╗███╗   ███╗███████╗
# ╚══██╔══╝██║  ██║██╔════╝████╗ ████║██╔════╝
#    ██║   ███████║█████╗  ██╔████╔██║█████╗
#    ██║   ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══╝
#    ██║   ██║  ██║███████╗██║ ╚═╝ ██║███████╗
#    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝
hc lock
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc pad 1 30 0 0 0
hc pad 0 30 0 0 0
hc set default_frame_layout 2
hc set_layout grid
hc set window_gap 15

# inner_color/inner_width
#       ╻        outer_color/outer_width
#       │                  ╻
#       │                  │
# ┌────╴│╶─────────────────┷─────┐ ⎫ border_width
# │     │      color             │ ⎬ + title_height
# │  ┌──┷─────────────────────┐  │ ⎭ + padding_top
# │  │====================....│  │
# │  │== window content ==....│  │
# │  │====================..╾──────── background_color
# │  │........................│  │
# │  └────────────────────────┘  │ ⎱ border_width +
# └──────────────────────────────┘ ⎰ padding_bottom

hc attr theme.active.color '#6DE879'
hc attr theme.normal.color '#151515'
hc attr theme.urgent.color '#F53F58'
hc attr theme.background_color '#000'



# Title
hc attr theme.title_height 17
hc attr theme.padding_top 5
hc attr theme.title_font 'Roboto:pixelsize=12'
hc attr theme.active.title_color '#000'
hc attr theme.normal.title_color '#d8d1c3'

# Outer border
hc attr theme.border_width 2
hc attr theme.active.outer_color '#3E4A00'

# Inner border
hc attr theme.inner_width 0
hc attr theme.inner_color #F00
hc attr theme.active.inner_color '#3E4A00'


# Floating
hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color '#6DE879'

# Frame
hc set frame_padding 0
hc set frame_normal_opacity 40
hc set frame_active_opacity 40
hc set frame_transparent_width 40
hc set frame_gap 5

hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set always_show_frame on
hc set frame_bg_transparent on


# Frame Border
hc set frame_border_width 0
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#353834'
hc set frame_bg_active_color '#697c5d'







# ██████╗ ██╗   ██╗██╗     ███████╗███████╗
# ██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
# ██████╔╝██║   ██║██║     █████╗  ███████╗
# ██╔══██╗██║   ██║██║     ██╔══╝  ╚════██║
# ██║  ██║╚██████╔╝███████╗███████╗███████║
# ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝

hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class~'Xfce4-(.+)' floating=on
hc rule class='VSCodium' tag=${tag_names[1]}
hc rule class='VSCodium' switchtag=on
hc rule class='Vivaldi-stable' tag=${tag_names[0]}
hc rule class='Vivaldi-stable' switchtag=on
hc rule class='discord' tag=${tag_names[8]}
hc rule class='Nm-connection-editor' floating=on
hc rule class='Seahorse' floating=on
hc rule class~'(.+).exe' floating=on
hc rule class='Genymotion Player' tag=${tag_names[7]}
hc rule class='dolphin' floating=on
hc rule class~'MEGAsync' floating=on
# hc rule class~'main.py' floating=on
hc rule class~'Spotify' tag=${tag_names[9]}

hc set tree_style '╾│ ├└╼─┐'


hc unlock

hc detect_monitors
autorandr -c

if hc silent new_attr bool my_not_first_autostart ; then
    # Window Manager
    hc reload
    python ~/.config/polybar/launch.py &
    picom &
    nitrogen --restore

    # General Apps
    discord-canary --start-minimized &
    # flameshot &
    bash /usr/local/bin/nagastart.sh &
    # redshift &
    # emote &
    nm-applet &
    # polychromatic-tray-applet &
    megasync &
fi

