# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  tym = {
    pname = "tym";
    version = "887bce3cf2057e58b6dba97c5126687fad559f47";
    src = fetchFromGitHub ({
      owner = "endaaman";
      repo = "tym";
      rev = "887bce3cf2057e58b6dba97c5126687fad559f47";
      fetchSubmodules = false;
      sha256 = "sha256-5pXNOuMT2/G+m6XoTrwNTCGNfISLLy0wQpVPhQJzs4s=";
    });
    date = "2023-02-12";
  };
  vte = {
    pname = "vte";
    version = "abb7afd06c64769ff8754d2d82edd660cee16c64";
    src = fetchgit {
      url = "https://gitlab.gnome.org/GNOME/vte";
      rev = "abb7afd06c64769ff8754d2d82edd660cee16c64";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-sGcEYzIF09k6vVaOcdxhYJYnXzLErDMhtxHnYnXsSKs=";
    };
    date = "2023-02-11";
  };
}
