# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  tym = {
    pname = "tym";
    version = "57e5e4bc312544d9ee03f628a016c4c6c5fbf852";
    src = fetchFromGitHub ({
      owner = "endaaman";
      repo = "tym";
      rev = "57e5e4bc312544d9ee03f628a016c4c6c5fbf852";
      fetchSubmodules = false;
      sha256 = "sha256-vcOEnBsxfCAtUFJyS7tFePTb6BkG+hzNQUYPm+sxz1I=";
    });
    date = "2023-01-30";
  };
  vte = {
    pname = "vte";
    version = "1d1896427fb28b0aa32f5dd401f2a86e97452cf1";
    src = fetchgit {
      url = "https://gitlab.gnome.org/GNOME/vte";
      rev = "1d1896427fb28b0aa32f5dd401f2a86e97452cf1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gwbSyrNLNiDXvcoLCauOmZftiYmYuMyVTQUeyDxcr0c=";
    };
    date = "2023-01-21";
  };
}
